### ISSUE TITLE
Extrair informações do corpo editorial

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/scielo-manager#1038]
A equipe de produção relatou a necessidade de extrair as informações do corpo editorial. Pensamos e decidimos que relatórios seria uma uma solução ideal.

Essa atividade será contemplada em outro momento, já que existe desenvolvimento com maior prioridade.

**Comment by gustavofonseca** [comment]
Vou fechar esse ticket, e esperar que quando os relatórios forem especificados sejam abertos tickets específicos e mensuráveis.
