### ISSUE TITLE
Sin acceso a scielo manager

### ISSUE THREAD

**Issue by cristinafraga** [scieloorg/scielo-manager#1052]
Buenos días,
Soy cristina Fraga,d el quipo scielo españa.
Escribo porque NO me funciona la cuenta que me crearon para acceder a scielo manager.
mi correo de acceso es cristinafraga@isciii.es

Gracias y reciban cordiales saludos,
Cristina

**Comment by gustavofonseca** [comment]
@cristinafraga, o problema já foi solucionado?

**Comment by jamilatta** [comment]
A coleção Espanha esta no ambiente de homologação, foi criado um usuário com e-mail:cbojo@isciii.es (cristina.bojo) não sei se é a mesma pessoal.

@cristinafraga por favor confirme que hay más de una Cristina en SciELO España!

**Comment by cristinafraga** [comment]
Hola,

Sim, ha mais de uma Cristina en Scielo España. Somos dois:

Cristina Bojo
Cristina Fraga

Cumprimentos,
Cristina


De: Gustavo Fonseca [mailto:notifications@github.com]
Enviado el: miércoles, 14 de enero de 2015 14:30
Para: scieloorg/scielo-manager
CC: Cristina Alexandra Fraga Medin
Asunto: Re: [scielo-manager] Sin acceso a scielo manager (#1052)


@cristinafraga<https://github.com/cristinafraga>, o problema já foi solucionado?

**Comment by gustavofonseca** [comment]
Estou assumindo que o problema já foi solucionado.

**Comment by cristinafraga** [comment]
Hola,

Si el problema ya está solucionado, ¿me pueden decir que usuario y clave tengo?.

Mi compañera cristina Bojo no sabe cuáles son sus claves. Su e-mail es: cbojo@isciii.es<mailto:cbojo@isciii.es> por si desean contactar directamente con ella.

Obrigada,
Cristina

De: Gustavo Fonseca [mailto:notifications@github.com]
Enviado el: viernes, 16 de enero de 2015 11:21
Para: scieloorg/scielo-manager
CC: Cristina Alexandra Fraga Medin
Asunto: Re: [scielo-manager] Sin acceso a scielo manager (#1052)


Estou assumindo que o problema já foi solucionado.

**Comment by gustavofonseca** [comment]
@cristinafraga, as credenciais podem ser recuperadas no link http://homolog.manager.scielo.org/accounts/password/reset/

Por favor me informe caso haja algum problema. 

-Gustavo

**Comment by cristinafraga** [comment]
Hola Gustavo,
Sí, yo tengo problemas con mi e-mail porque introduzco cristinafraga@isciii.es<mailto:cristinafraga@isciii.es> y me dice que:


  *   “Esta dirección de correo electrónico no tiene una cuenta de usuario asociada. ¿Está seguro de que se ha registrado?”
Gracias

De: Gustavo Fonseca [mailto:notifications@github.com]
Enviado el: viernes, 16 de enero de 2015 13:42
Para: scieloorg/scielo-manager
CC: Cristina Alexandra Fraga Medin
Asunto: Re: [scielo-manager] Sin acceso a scielo manager (#1052)


@cristinafraga<https://github.com/cristinafraga>, as credenciais podem ser recuperadas no link http://homolog.manager.scielo.org/accounts/password/reset/

Por favor me informe caso haja algum problema.

-Gustavo

**Comment by cristinafraga** [comment]
Hola de nuevo,

¡Ya puedo acceder!. Tuve que introducir una nueva contraseña.

Muchas muchas gracias, ☺
Cristina

De: Gustavo Fonseca [mailto:notifications@github.com]
Enviado el: viernes, 16 de enero de 2015 13:42
Para: scieloorg/scielo-manager
CC: Cristina Alexandra Fraga Medin
Asunto: Re: [scielo-manager] Sin acceso a scielo manager (#1052)


@cristinafraga<https://github.com/cristinafraga>, as credenciais podem ser recuperadas no link http://homolog.manager.scielo.org/accounts/password/reset/

Por favor me informe caso haja algum problema.

-Gustavo

**Comment by gustavofonseca** [comment]
Olá Cristina, realmente ainda não havia uma conta criada para o seu usuário. 

Qualquer dúvida pode escrever para gustavo dot fonseca at scielo dot org

-Gustavo

**Comment by cristinafraga** [comment]
Olá Gustavo,

Me acaba de llegar un mensaje para cambiar la contraseña, la cambié y ya pude acceder… ¡¡funciona!!

OBRIGADA,
Cristina

De: Gustavo Fonseca [mailto:notifications@github.com]
Enviado el: viernes, 16 de enero de 2015 13:55
Para: scieloorg/scielo-manager
CC: Cristina Alexandra Fraga Medin
Asunto: Re: [scielo-manager] Sin acceso a scielo manager (#1052)

Olá Cristina, realmente ainda não havia uma conta criada para o seu usuário.

Qualquer dúvida pode escrever para gustavo dot fonseca at scielo dot org

-Gustavo
