### ISSUE TITLE
Adicionar Thrift no requirements.txt 

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/scielo-manager#1070]
Adicionar o pacote no requirement.txt.

**Comment by jfunez** [comment]
?
Imagino que esta falando de: *thriftpy* e não de *thirft*.
Mesmo assim, já foi incluído no requirements.txt no branch (1036_integracao_thrift) que é aonde  estamos desenvolvendo os serviços.
https://github.com/scieloorg/scielo-manager/blob/1036_integracao_thrift/requirements.txt#L25

tem que ser adicionado em outro lugar @jamilatta?

**Comment by jamilatta** [comment]
Não entendi...

pq estou instalando pelo branch *beta* e ele importa o thrift, acredito que
no *beta* já exista códigos em thrift, porém o arquivo requirements.txt não
indica o thrift para instalação.



2015-02-25 14:45 GMT-03:00 Juan Funez <notifications@github.com>:

> ?
> Imagino que esta falando de: *thriftpy* e não de *thirft*.
> Mesmo assim, já foi incluído no requirements.txt no branch
> (1036_integracao_thrift) que é aonde estamos desenvolvendo os serviços.
>
> https://github.com/scieloorg/scielo-manager/blob/1036_integracao_thrift/requirements.txt#L25
>
> tem que ser adicionado em outro lugar @jamilatta
> <https://github.com/jamilatta>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scieloorg/scielo-manager/issues/1070#issuecomment-76015435>
> .
>



-- 
Atenciosamente,

Jamil Atta Junior

**Comment by jfunez** [comment]
tem como identificar qual código esta importando *thrift* ou *thriftpy*?

se não me engano, todo o desenvolvimento relacionado com o serviços, foi feito no branch: *1036_integracao_thrift*
e se tiver algum código no branch beta deve ser removido/ajustado.

**Comment by jamilatta** [comment]
Esta no settings.py.

2015-02-25 15:15 GMT-03:00 Juan Funez <notifications@github.com>:

> tem como identificar qual código esta importando *thrift* ou *thriftpy*?
>
> se não me engano, todo o desenvolvimento relacionado com o serviços, foi
> feito no branch: *1036_integracao_thrift*
> e se tiver algum código no branch beta deve ser removido/ajustado.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scieloorg/scielo-manager/issues/1070#issuecomment-76021435>
> .
>



-- 
Atenciosamente,

Jamil Atta Junior

**Comment by jfunez** [comment]
Então... eu não achei!
estou vendo settings no beta: https://github.com/scieloorg/scielo-manager/blob/beta/scielomanager/scielomanager/settings.py#L148

**Comment by jamilatta** [comment]
Desconsiderar a tarefa.

On Wed, Feb 25, 2015 at 3:28 PM, Juan Funez <notifications@github.com>
wrote:

> Então... eu não achei!
> estou vendo settings no beta:
> https://github.com/scieloorg/scielo-manager/blob/beta/scielomanager/scielomanager/settings.py#L148
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scieloorg/scielo-manager/issues/1070#issuecomment-76024432>
> .
>



-- 
Atenciosamente,

Jamil Atta Junior
