### ISSUE TITLE
Interface quebrada na listagem de artigos de um fascículo [branch 1036_integracao_thrift]

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/scielo-manager#1078]
![screen shot 2015-03-30 at 14 37 18](https://cloud.githubusercontent.com/assets/161335/6902472/5e177b1c-d6ea-11e4-9214-815708dd5504.png)

**Comment by jfunez** [comment]
principal suspeito:
``<tr>`` sem fechar.
https://github.com/scieloorg/scielo-manager/blob/1036_integracao_thrift/scielomanager/journalmanager/templates/journalmanager/article_list.html#L45

**Comment by jfunez** [comment]
feito em PR #1080
