### ISSUE TITLE
Ajuste no formulário de cadastro de revista

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/scielo-manager#1081]
Diante da experiência com os usuários da SciELO, verificamos que os botões "Salvar" e "Cancelar" devem ficar ao lado do botão "Salva e continuar depois" ou o botão "Salva e continuar depois" deve ficar no final do formulário.

**Comment by jfunez** [comment]
@jamilatta gostaria de saber mais sobre os detalhes de essa experiência com usuários.

É muito difícil conseguir um layout que todo o mundo goste, principalmente porque tem o fator do "gosto pessoal" e as costumes. E sempre tem alternativas que são utilizadas em diferentes plataformas.

No momento foi discutido o motivo do layout atual, inclusive lembro que @gustavofonseca comentou sobre a alternativa de colocar o botão de "cancelar" como um link e não como um botão.
a motivação do layout atual foi simples:
- o usuário geralmente não faz click em cancelar
- o usuário da uma olhada nas opções que tem para clickar
- facilmente o botão vermelho indica "atenção pode ser perigoso" (não queremos que cancele, lembra do botão/link para fazer Delete no admin do django)
- o movimento do olho de esquerda a direita, de cima para abaixo, finaliza com a execução da ação principal, não tem que voltar para o lado esquerdo. (isso mas bem justifica a posição relativa entre os botões e não a distancia entre eles) 
- a distancia evita erros dos usuários

As alternativas são muitas (pelo menos 6 que eu imagino agora), e agora lendo rápido um artigo[0], vejo que as ações como "salvar e continuar" é considerado uma ação secundária, ou seja um link, mas atualmente está com ação primaria, competindo como o submit.

Algumas perguntas:
- Realmente melhoraria muito a UX uma mudança assim? o como diz [1]: It doen't matter?
- Será que é necessário ter botão de cancelar mesmo?
- Precisamos ter guidelines para as interfaces no manager?

Refs:
[0] http://uxmovement.com/buttons/why-ok-buttons-in-dialog-boxes-work-best-on-the-right/
[1] http://ux.stackexchange.com/a/54
[2] http://www.nngroup.com/articles/ok-cancel-or-cancel-ok/
[3] http://www.lukew.com/ff/entry.asp?571
[4] https://ux.stackexchange.com/questions/19/is-there-a-recommended-location-for-a-submit-button-in-relation-to-a-cancel-on-t

**Comment by jamilatta** [comment]
Acho que não soube me expressar suficientemente bem para seu entendimento:

Não estou questionando a disposição do botão Cancelar e Salvar, menciono que deveríamos manter um único local para ficar as ações do formulário, o que não acontece atualmente... em consequência o usuário acaba utilizando o primeiro botão que encontra visível no caso o "Salva e continuar depois". 

Acho interessante verificarmos referência para analisarmos com mais segurança, mas precisamos analisarmos com base em nosso contexto links não vão me convencer ao que o usuário diz, sente e comumente utiliza.

Passamos por tal situação hoje onde a Eliana clicou no botão "Salva e continuar depois" pensando que havia salvo e acabou não encontrando a revista que estava no dashboard dela. Acredito também que o sistema não tem um ritmo intenso de cadastro de revista (isso justifica não precisamos nos preocupar com isso **agora**), mas se caso tivéssemos iríamos passar por essa situação com mais frequência(acredito). 

A idéia não é perdermos tempo com isso, o ticket esta aí e deve ser analisado considerando o usuário daqui, da SicELO.

**Comment by jamilatta** [comment]
Quando menciono **SciELO** me refiro a **Rede SciELO**.

**Comment by jfunez** [comment]
Suspeito que meu entendimento não seja o melhor, mas a segunda mensagem não diz o mesmo que a primeira, e inclusive é contraditório em alguns pontos.

primeiro:
- "Diante da experiência com os usuário da SciELO,". Entendi que experiência foi com mas de um usuário.
- "Passamos por tal situação hoje onde a Eliana". A experiência foi só com um usuário

depois:
- "verificamos que os botões "Salvar" e "Cancelar devem ficar ao lado do botão ..."
- "Não estou questionando a disposição do botão Cancelar e Salvar, "

Como foi questionada a posição dos botões na primeira mensagem, gerou a minha explicação de antecedentes e referencias.

E complementando:
"menciono que deveríamos manter um único local para ficar as ações do formulário, o que não acontece atualmente"
Por isso comento que seria bom ter algum guideline. tentamos manter o padrão dos botões para todos os forms do manager.

"Acho interessante verificarmos referência para analisarmos com mais segurança"
sim, sem duvida, por isso deixei alguns links para começar.

"...mas precisamos analisarmos com base em nosso contexto "
claro, sem duvida.

"links não vão me convencer ao que o usuário diz, sente e comumente utiliza."
convencer? Para resolver este tipo de problemas é que existem os padrões de UI.
Os links são referencias a estúdios realizados, e padrões de UI, que foram avaliados por pessoas mais idôneas, e se reparar em nenhuma das referencias dizem que tem que usar uma opção ou outra.
tem muitas opções que se ajustam a diversos cenários. A ideia é abrir uma discussão e não usar os links como "texto sagrado".

"Eliana clicou no botão "Salva e continuar depois" pensando que havia salvo e acabou não encontrando a revista que estava no dashboard dela."
Pode ser que o problema seja resolvido com um aviso para o usuário, e não com a mudança nos botões. Ou seja é um problema de UX, em geral, o manager tem vários "problemas" de UX porque nunca (que eu saiba) foi analisado desde esse ponto de vista.

"Acredito também que o sistema não tem um ritmo intenso de cadastro de revista" 
concordamos em que não é uma mudança urgente.

Finalmente:
"Quando menciono SciELO me refiro a Rede SciELO." 
Você não mencionou "SciELO", mencionou "SicELO" e igualmente eu entendi que se referia aos usuários da rede.

Em fim, o que tentei explicar foi que, existiu sim um mínimo de critérios sobre a posição dos botões, e que tem referencias a artigos que estudam em profundidade as alternativas no caso de querer mudar. Isso se realmente perceber como um problema a experiência de um usuário. Considerando também que existem outros problemas de UX a serem analisados e resolvidos.
O problema não é mudar a posição de um botão, isso é feito frequentemente, mas sim que falta analise do manager como um produto e não como um monte de formulários e listas. 

HTH!

**Comment by jamilatta** [comment]
Melhorando a msg: 

Diante a conversa que tivemos com a Eliana verifiquei que os botões "Salvar" e "Cancelar" devem ficar ao lado do botão **"Salva e continuar depois"** ou o botão **"Salva e continuar depois"** deve ficar no final do formulário.

**Comment by gustavofonseca** [comment]
Uma única confusão de alguém que não utiliza o sistema frequentemente não pode ser considerada falha, deficiência ou ponto de melhoria do sistema. Sugiro fechar o ticket.

-Gustavo

**Comment by jamilatta** [comment]
Descordo, como havia comentado não é preciso ser feito, mas acredito que deve ser registrado.

**Comment by jamilatta** [comment]
Durante um longo período de utilização... isso não voltou a ocorrer! o que justifica que esse ticket é inútil, caso esse tipo de engano volte a ocorrer reabriremos.
