### ISSUE TITLE
[Transifex] Automatic update of the source file of English in SciELO Manager failed

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/scielo-manager#1082]
O Transifex está sinalizando um erro de sintaxe na tradução para inglês, segue e-mail enviado automaticamente, repare que não foi possível indicar a linha:

We have not been able to update the source file for the resource English of the project SciELO Manager.

The URL we used to update the source file from was https://raw.github.com/scieloorg/SciELO-Manager/master/scielomanager/scielomanager/locale/en_US/LC_MESSAGES/django.po.

The exact error we encountered was:

There is a syntax error in your file. Line

**Comment by jfunez** [comment]
@jamilatta este problema continua acontecendo?

**Comment by jamilatta** [comment]
@jfunez 

não, vou fechar esse ticket até que isso volte a ocorrer.
