### ISSUE TITLE
Remover a capacidade de validar XMLs remotos

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/scielo-manager#1083]
Na interface do *stylechecker*, atualmente é possível carregar o XML objeto de validação de duas maneiras: 1) Via URL pública do recurso e 2) Via upload.

A maneira 1 deve ser removida por conta de: 1) Representar um problema de segurança ao permitir que o servidor realize requisições HTTP para servidores não confiáveis e 2) Trata-se de uma funcionalidade não utilizada.

**Comment by jfunez** [comment]
Resolvido em b671d7f
