### ISSUE TITLE
Remover app *editorialmanager* do branch principal

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/scielo-manager#1084]
Trata-se de 5183 linhas de código e 4 tabelas no banco de dados não utilizadas, que potencialmente abrigam inúmeros bugs e td que há de mais sombrio. 

Sugiro que a aplicação seja mantida em um branch próprio até que seja necessária sua re-incorporação para uso imediato.

**Comment by jamilatta** [comment]
Em conversa com o a equipe de desenvolvimento...., decidimos marcar uma reunião com a **equipe responsável** pelo utilização, nessa reunião discutiremos uma data para uso imediato.

**Comment by jamilatta** [comment]
Reunião realizada no dia 14/05/2015:

Decidimos que a equipe composta pelos colaboradores: Alex Mendonça, Fabio Almeida e Isabela Fonseca iram iniciar a capacitação de outros colaboradores.... que será definido na reunião do dia **20/05/2015** , essa reunião visa capacitar o uso da ferramenta bem como a estratégia de cadastro inicial do corpo editorial da revista de Saúde Pública. 

Decidimos que independente da utilização desse cadastro iremos considerar a ferramenta como sendo o local onde esses dados serão atualizados e que futuras demandas serão reportadas no sistema de ticket do projeto.

Vale ressaltar que após a implementação da nova interface do site SciELO esses dados ficaram disponíveis a partir dessa ferramenta, concordamos que essa fase é realmente necessária para que seja alterado a cultura da SciELO para esse novo cenário.

Nem todos os envolvidos participaram da reunião por conta disso peço para que as pessoas que tenham dúvida ou queiram opinar sobre algum dos pontos, entrem em contato com os seguintes colaboradores: @jamilatta, @alexxxmendonca e @jfunez.

**Comment by alexxxmendonca** [comment]
De acordo.

A ferramenta será utilizada, principalmente, pela equipe de produção, que
até então não tem conhecimento da ferramenta. Portanto, a avaliação da
partes dele é fundamental. A reunião do dia 20/05/2015 definirá os próximos
passos para a consolidação da ferramenta.

*--*
*Alex Mendonça*
*SciELO *
*FAPESP - CNPq - BIREME - **FAP UNIFESP*
*Av. Onze de Junho, 269*
*04041-050 - São Paulo-SP - Brasil*
*Tel.: 55-11-5083-3639 Ramal/Ext. 113*
*www.scielo.org <http://www.scielo.org> | www.scielo.br
<http://www.scielo.br> | blog.scielo.org <http://blog.scielo.org>*

Inscreva-se
<http://scielo.us4.list-manage.com/subscribe?u=f26dcf71797dd37381acb4aa5&id=815cbad617>
na newsletter mensal *SciELO em Perspectiva*: informação e conhecimento
orientado para o desenvolvimento da comunicação científica.

Sign up
<http://scielo.us4.list-manage1.com/subscribe?u=f26dcf71797dd37381acb4aa5&id=cd8ad67f4c>
to
the *SciELO in Perspective* monthly newsletter: information and knowledge
oriented to the development of scientific communication.

2015-05-14 13:49 GMT-03:00 Jamil Atta Junior <notifications@github.com>:

**Comment by jamilatta** [comment]
Ciente.

**Comment by jfunez** [comment]
EditorialManager foi habilitado em produção.
