### ISSUE TITLE
Remover app *articletrack* do branch principal

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/scielo-manager#1085]
Reparei que não somente a app *editorialmanager* é uma app não utilizada, também temos a app *articletrack*, seguindo os mesmo critérios do ticket #1084, sugiro que a app *articletrack* seja removida e incorporada quando finalizada.

**Comment by gustavofonseca** [comment]
Estou de acordo.

**Comment by jfunez** [comment]
```
jfunez created feature_articletrack from beta (+0 new commits):
https://github.com/scieloorg/scielo-manager/commits/feature_articletrack
```

**Comment by jfunez** [comment]
App removida em PR: #1094 
Novos desenvolvimentos devem ser feitos no brach: **feature_articletrack**
