### ISSUE TITLE
Remover sistema de *waffles*

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/scielo-manager#1091]
*Waffle* é um mecanismo que permite que regiões do código sejam acessadas conforme regras arbitrárias, e é utilizado para que funcionalidades ainda em desenvolvimento possam fazer parte da base de código principal. O problema é que o uso desse mecanismo tem facilitado a existência de lixo na base de código principal. Muito lixo.

Os novos mandamentos:
* Códigos só devem ser escritos quando não há mais nada a ser feito.
* Códigos só devem ser incorporados nos branches **beta** e **master** quando não há mais como impedir o usuário de utilizá-los, em produção.

Amém.

**Comment by jamilatta** [comment]
De acordo, dessa forma podemos manter somente os códigos que serão
utilizados.

2015-05-05 11:23 GMT-03:00 Gustavo Fonseca <notifications@github.com>:

> *Waffle* é um mecanismo que permite que regiões do código sejam acessadas
> conforme regras arbitrárias, e é utilizado para que funcionalidades ainda
> em desenvolvimento possam fazer parte da base de código principal. O
> problema é que o uso desse mecanismo tem facilitado a existência de lixo na
> base de código principal. Muito lixo.
>
> Os novos mandamentos:
>
>    - Códigos só devem ser escritos quando não há mais nada a ser feito.
>    - Códigos só devem ser incorporados nos branches *beta* e *master*
>    quando não há mais como impedir o usuário de utilizá-los, em produção.
>
> Amém.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scieloorg/scielo-manager/issues/1091>.
>



-- 

Jamil Atta Junior

**Comment by jfunez** [comment]
[IMPEDIDO] 
 depende da aprovação do PR: #1094 e a integração do EditorialManager na produção.

**Comment by jfunez** [comment]
aguardando aprovação do PR:  #1136 
assim que for aprovado só falta remover a aplicação (settings, requirements, etc) do sistema
