### ISSUE TITLE
Alteração na ordem dos atributos de um membro do corpo editorial

### ISSUE THREAD

**Issue by almeida-fabio** [scieloorg/scielo-manager#1095]
Prezados, ao preencher os dados de cada membro do corpo editorial, notamos que o campo e-mail sempre vem em primeiro, nas páginas informativas do site atual, esse campo sempre permanece por último entre os atributos. Vocês poderiam então fazer essa troca na ordem dos atributos? Segue imagem para ilustrar:

![e-mail](https://cloud.githubusercontent.com/assets/8592848/7635080/3b143ede-fa35-11e4-8a93-51091299411f.png)

Obrigado.

**Comment by jamilatta** [comment]
Sim faremos.

**Comment by jfunez** [comment]
@jamilatta @almeida-fabio : 
é possível mudar isso sim, mas é realmente necessário?
lembremos que o layout atual que aparece na imagem, não é e não vai ser o layout do site publico.
se for realmente necessário podemos fazer a mudança, mas acho que podemos deixar esta tarefa com prioridade bem baixa.

**Comment by jamilatta** [comment]
Concordo.

**Comment by almeida-fabio** [comment]
Sem problemas Juan e Jamil. Deixo apenas registrado para ser feito futuramente então.
