### ISSUE TITLE
Ordem de números - scielo-manager

### ISSUE THREAD

**Issue by javani** [scieloorg/scielo-manager#1097]
No manager, a BWHO v93n5 foi criada antes dos números 3 e 4. Apesar do preenchimento correto, o número ficou fora da ordem. Acredito que o que deva mandar na ordenação seja o número e não a data de criação. 
http://manager.scielo.org/journal/31/issue/
http://homolog.xml.scielosp.org/scielo.php?script=sci_issues&pid=0042-9686&lng=en&nrm=iso

**Comment by gustavofonseca** [comment]
O que manda na ordenação é o atributo "order" que é invisível para os usuários do scielomanager, mas compõe o PID dos artigos associados a ele. Por esse motivo atualmente ele é imutável.

**Comment by javani** [comment]
Como resolver? Temos que deletar a issue e cadastrar novamente?

**Comment by gustavofonseca** [comment]
Não há o que ser feito. Os fascículos já foram publicados e agora a formação do PID não pode mais ser alterada.

**Comment by javani** [comment]
Tem como excluir o número? Não podemos deixar a grade errada.
Isso tem que ser pensando pois provavelmente teremos casos semelhantes
quando houver mais de uma pessoa manejando os números no manager.

Em 28 de maio de 2015 14:39, Gustavo Fonseca <notifications@github.com>
escreveu:

> Não há o que ser feito. Os fascículos já foram publicados e agora a
> formação do PID não pode mais ser alterada.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scieloorg/scielo-manager/issues/1097#issuecomment-106516121>
> .
>



-- 
Javani Araujo
*SciELO Brasil*
*FAPESP - CNPq - BIREME - **FAP UNIFESP*
*Av. Onze de Junho, 269*
*04041-050 - São Paulo-SP - Brasil*
*Tel.: 55-11-5083-3639*
*www.scielo.org <http://www.scielo.org/> | www.scielo.br
<http://www.scielo.br/> | blog.scielo.org <http://blog.scielo.org/>*

**Comment by gustavofonseca** [comment]
Infelizmente não é possível. O número já foi publicado e essa alteração quebraria todos os links, incluindo do DOI.

**Comment by javani** [comment]
Neste caso não, pois o DOI não é provido por nós e não fazemos o envio do
SciELO SP para WoS, nem para nenhuma outra base, que eu saiba.
Tem que haver uma solução para isso. Talvez não formar a apresentação do
sumário pela data de inclusão no manager mas pela sequencia de volume,
número e ano ou só volume e ano ou número e ano dependendo da
característica da revista ou ter outro jeito para formação do ID.
Tem-se que pensar que erros acontecem e que eles devem ser passíveis de
correção. Nesse caso em específico, todos os 3 números foram processados
juntos, mas o envio ao homolog.xml foi feito na ordem em que os mesmos
ficaram prontos.
Isso provavelmente irá acontecer com frequência quando vários usuários
puderem incluir os dados no manager, fazerem os envios dos pacotes
individualizados de artigos quando os números forem criados e fechados
aleatoriamente, ou seja, quando se puder começar um número sem o outro
estar fechado etc.


Em 29 de maio de 2015 10:29, Gustavo Fonseca <notifications@github.com>
escreveu:

> Infelizmente não é possível. O número já foi publicado e essa alteração
> quebraria todos os links, incluindo do DOI.
>
>
> > On 28/05/2015, at 14:48, javani <notifications@github.com> wrote:
> >
> > Tem como excluir o número? Não podemos deixar a grade errada.
> > Isso tem que ser pensando pois provavelmente teremos casos semelhantes
> > quando houver mais de uma pessoa manejando os números no manager.
> >
> > Em 28 de maio de 2015 14:39, Gustavo Fonseca <notifications@github.com>
> > escreveu:
> >
> > > Não há o que ser feito. Os fascículos já foram publicados e agora a
> > > formação do PID não pode mais ser alterada.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/scieloorg/scielo-manager/issues/1097#issuecomment-106516121
> >
> > > .
> > >
> >
> >
> >
> > --
> > Javani Araujo
> > *SciELO Brasil*
> > *FAPESP - CNPq - BIREME - **FAP UNIFESP*
> > *Av. Onze de Junho, 269*
> > *04041-050 - São Paulo-SP - Brasil*
> > *Tel.: 55-11-5083-3639*
> > *www.scielo.org <http://www.scielo.org/> | www.scielo.br
> > <http://www.scielo.br/> | blog.scielo.org <http://blog.scielo.org/>*
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/scieloorg/scielo-manager/issues/1097#issuecomment-106523619
> >.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scieloorg/scielo-manager/issues/1097#issuecomment-106802811>
> .
>



-- 
Javani Araujo
*SciELO Brasil*
*FAPESP - CNPq - BIREME - **FAP UNIFESP*
*Av. Onze de Junho, 269*
*04041-050 - São Paulo-SP - Brasil*
*Tel.: 55-11-5083-3639*
*www.scielo.org <http://www.scielo.org/> | www.scielo.br
<http://www.scielo.br/> | blog.scielo.org <http://blog.scielo.org/>*

**Comment by gustavofonseca** [comment]
Javani, eu compreendo sua reação mas não se trata de algo novo. Na realidade é uma característica que o SciELO possui desde muito tempo, talvez desde o início. O valor da ordem do fascículo é utilizado para formar o PID, que por sua vez é utilizado para formar a URL do artigo. Imagina que bagunça aconteceria se o PID de um artigo fosse trocado pelo de outro!

Quando esse tipo de erro ocorrer, vocês devem entrar em contato conosco antes que o número seja publicado no site final. Depois da publicação nós não podemos fazer mais nada.

**Comment by javani** [comment]
Olá Gustavo,
Sei que isso tem que ser verificado antes, mas passou. E isto já ocorreu no
passado algumas vezes, não me recordo quantas, inclusive com remanejamento
de números quando havia suplemento e issues preenchidas erradas, uma vez
que os mesmos não chegavam na ordem e a pessoa acabava preenchendo a ordem
errada. Acho que a Roberta pode esclarecer melhor. A ABC é um caso onde
isto ocorreu.
Houve casos, inclusive, de exclusão de issue.
De qualquer forma, temos que resolver este problema e pensar numa forma de
como isso ser sanado no futuro. Talvez com avisos aos usuário.

Em 29 de maio de 2015 13:51, Gustavo Fonseca <notifications@github.com>
escreveu:

> Javani, eu compreendo sua reação mas não se trata de algo novo. Na
> realidade é uma característica que o SciELO possui desde muito tempo,
> talvez desde o início. O valor da ordem do fascículo é utilizado para
> formar o PID, que por sua vez é utilizado para formar a URL do artigo.
> Imagina que bagunça aconteceria se o PID de um artigo fosse trocado pelo de
> outro!
>
> Quando esse tipo de erro ocorrer, vocês devem entrar em contato conosco
> antes que o número seja publicado no site final. Depois da publicação nós
> não podemos fazer mais nada.
>
>
> > On 29/05/2015, at 11:16, javani <notifications@github.com> wrote:
> >
> > Neste caso não, pois o DOI não é provido por nós e não fazemos o envio do
> > SciELO SP para WoS, nem para nenhuma outra base, que eu saiba.
> > Tem que haver uma solução para isso. Talvez não formar a apresentação do
> > sumário pela data de inclusão no manager mas pela sequencia de volume,
> > número e ano ou só volume e ano ou número e ano dependendo da
> > característica da revista ou ter outro jeito para formação do ID.
> > Tem-se que pensar que erros acontecem e que eles devem ser passíveis de
> > correção. Nesse caso em específico, todos os 3 números foram processados
> > juntos, mas o envio ao homolog.xml foi feito na ordem em que os mesmos
> > ficaram prontos.
> > Isso provavelmente irá acontecer com frequência quando vários usuários
> > puderem incluir os dados no manager, fazerem os envios dos pacotes
> > individualizados de artigos quando os números forem criados e fechados
> > aleatoriamente, ou seja, quando se puder começar um número sem o outro
> > estar fechado etc.
> >
> >
> > Em 29 de maio de 2015 10:29, Gustavo Fonseca <notifications@github.com>
> > escreveu:
> >
> > > Infelizmente não é possível. O número já foi publicado e essa alteração
> > > quebraria todos os links, incluindo do DOI.
> > >
> > >
> > > > On 28/05/2015, at 14:48, javani <notifications@github.com> wrote:
> > > >
> > > > Tem como excluir o número? Não podemos deixar a grade errada.
> > > > Isso tem que ser pensando pois provavelmente teremos casos
> semelhantes
> > > > quando houver mais de uma pessoa manejando os números no manager.
> > > >
> > > > Em 28 de maio de 2015 14:39, Gustavo Fonseca <
> notifications@github.com>
> > > > escreveu:
> > > >
> > > > > Não há o que ser feito. Os fascículos já foram publicados e agora a
> > > > > formação do PID não pode mais ser alterada.
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > >
> https://github.com/scieloorg/scielo-manager/issues/1097#issuecomment-106516121
> > > >
> > > > > .
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > > Javani Araujo
> > > > *SciELO Brasil*
> > > > *FAPESP - CNPq - BIREME - **FAP UNIFESP*
> > > > *Av. Onze de Junho, 269*
> > > > *04041-050 - São Paulo-SP - Brasil*
> > > > *Tel.: 55-11-5083-3639*
> > > > *www.scielo.org <http://www.scielo.org/> | www.scielo.br
> > > > <http://www.scielo.br/> | blog.scielo.org <http://blog.scielo.org/>*
> > > > —
> > > > Reply to this email directly or view it on GitHub <
> > >
> https://github.com/scieloorg/scielo-manager/issues/1097#issuecomment-106523619
> > > >.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/scieloorg/scielo-manager/issues/1097#issuecomment-106802811
> >
> > > .
> > >
> >
> >
> >
> > --
> > Javani Araujo
> > *SciELO Brasil*
> > *FAPESP - CNPq - BIREME - **FAP UNIFESP*
> > *Av. Onze de Junho, 269*
> > *04041-050 - São Paulo-SP - Brasil*
> > *Tel.: 55-11-5083-3639*
> > *www.scielo.org <http://www.scielo.org/> | www.scielo.br
> > <http://www.scielo.br/> | blog.scielo.org <http://blog.scielo.org/>*
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/scieloorg/scielo-manager/issues/1097#issuecomment-106821412
> >.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scieloorg/scielo-manager/issues/1097#issuecomment-106869281>
> .
>



-- 
Javani Araujo
*SciELO Brasil*
*FAPESP - CNPq - BIREME - **FAP UNIFESP*
*Av. Onze de Junho, 269*
*04041-050 - São Paulo-SP - Brasil*
*Tel.: 55-11-5083-3639*
*www.scielo.org <http://www.scielo.org/> | www.scielo.br
<http://www.scielo.br/> | blog.scielo.org <http://blog.scielo.org/>*

**Comment by gustavofonseca** [comment]
Eu concordo. Mas creio que vai ser possível apenas quando tivermos com um novo site.

**Comment by javani** [comment]
@gustavofonseca vamos dar o treinamento para rede e precisamos saber como abordar essa questão que acredito não foi solucionada (ou foi?).
![image](https://cloud.githubusercontent.com/assets/912953/13987098/bdc94152-f0e4-11e5-883c-ad8dafdab0f5.png)
Se todos os números do ano fossem registrados na ordem no manager, mesmo sem artigos, resolveria o problema?

**Comment by gustavofonseca** [comment]
Não houve nenhum desenvolvimento relacionado a esse tópico. As
recomendações são as que vocês já conhecem e seguem. Registrar
previamente todos os números de um ano é uma abordagem possível, mas não
muda o fato e as limitações impostas pela imutabilidade da sua
ordenação.

-Gustavo

Em Qua 23 mar. 2016, às 10:50, javani escreveu:
