### ISSUE TITLE
Ordem dos membros do corpo editorial

### ISSUE THREAD

**Issue by almeida-fabio** [scieloorg/scielo-manager#1099]
Os membros do corpo editorial devem ser organizados em ordem alfabética e não em ordem de preenchimento como acontece atualmente.

**Comment by jamilatta** [comment]
Item realizado, estou aguardando aprovação da equipe para que possamos atualizar o ambiente de homologação para testes.

**Comment by alexxxmendonca** [comment]
Aguardando a aprovação da equipe para atualizar o ambiente de homologação? Como a equipe vai testar se ainda não está no ambiente de homologação?

**Comment by jamilatta** [comment]
Ainda não estou no aguardo aprovação da equipe de desenvolvimento, ver PR  https://github.com/scieloorg/scielo-manager/pull/1122.

**Comment by alexxxmendonca** [comment]
Ok!

**Comment by jamilatta** [comment]
@alexxxmendonca @almeida-fabio 

por gentileza realizem a validação utilizando a seguinte URL: http://192.168.169.176:8000.

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://192.168.169.176:8000/

**Comment by jamilatta** [comment]
OK!
