### ISSUE TITLE
E-mail do editor no corpo editorial

### ISSUE THREAD

**Issue by almeida-fabio** [scieloorg/scielo-manager#1100]
Futuramente, seria interessante uma opção, para o uso dos editores, onde eles escolheriam se desejariam manter visível na apresentação do corpo editorial o e-mail do editor-chefe ou se esse ficaria apenas registrado internamente para a nossa equipe.

**Comment by jfunez** [comment]
Assumindo que se trata da visibilidade no sites públicos.
Nesse caso teríamos que definir quais dados vão ficar visíveis (não somente o email), e isso esta relacionado ao layout do site.
Vou fechar este ticket, e quando aparecer a necessidade concreta pode ser reaberto ou referenciado desde um novo.
