### ISSUE TITLE
Ordenação de preenchimento no formulário: País antes de estado e cidade

### ISSUE THREAD

**Issue by almeida-fabio** [scieloorg/scielo-manager#1101]
No preenchimento no formulário o país poderia estar localizado antes do estado e cidade no momento do preenchimento. Talvez também pudesse ser explorada alguma listagem num banco de dados com estados e cidades a serem carregados automaticamente de acordo com o país definido pelo usuário.

**Comment by gustavofonseca** [comment]
Pensando que trata-se de uma aplicação que será utilizada por todas as coleções, você acha viável a gente ter esse tipo de informação de estados e cidades num nível de mundo?

**Comment by almeida-fabio** [comment]
@gustavofonseca Sim, achamos que isso seria viável, mas se isso for algo muito complexo, se fosse possível à princípio termos uma lista padronizada de estados e cidades quando o país for "Brazil" já seria bastante interessante.

**Comment by jamilatta** [comment]
Acredito que com o uso do Wayta esse ticket passa a não ter tanta significância, portanto irei fecha-lo, no futuro podemos reconsiderar.
