### ISSUE TITLE
Preenchimento obrigatório de cidade e estado

### ISSUE THREAD

**Issue by almeida-fabio** [scieloorg/scielo-manager#1102]
Estudar a possibilidade de tornar os campos "cidade" e "estado" obrigatórios para o preenchimento visando futuros relatórios.

**Comment by jamilatta** [comment]
Esse ticket não faz mais sentido uma vez que estamos utilizando as informações do Wayta para preenchimento dos campos de Cidade de Estado, vou fechar esse ticket no futuro se acharmos necessário reabrimos.
