### ISSUE TITLE
Preenchimento do País

### ISSUE THREAD

**Issue by almeida-fabio** [scieloorg/scielo-manager#1103]
Quando se salva um registro sem escolher o país a aplicação avança automaticamente mantendo como registrado o primeiro da lista: Afeganistão. Seria necessário alterar isso para que o usuário precise escolher um país (não deve haver um país padrão na lista) e não possa avançar sem preencher esse dado.

**Comment by jamilatta** [comment]
Estou corrigindo.

**Comment by jamilatta** [comment]
@almeida-fabio 

analisando com mais calma, vi que esse atributo é obrigatório isso justifica o fato de não ser possível selecionar um item vazio.

**Comment by jamilatta** [comment]
O ticket https://github.com/scieloorg/scielo-manager/issues/1039, confirma que o item deve ser obrigatório.

**Comment by jamilatta** [comment]
Posso fechar esse ticket?

**Comment by almeida-fabio** [comment]
@jamilatta , por enquanto vamos deixar esse ticket ainda aberto e discutiremos esse item na nossa próxima reunião para definirmos o preenchimento do país, ok?

**Comment by jamilatta** [comment]
OK.

2015-06-12 14:54 GMT-03:00 Fábio Almeida <notifications@github.com>:

> @jamilatta <https://github.com/jamilatta> , por enquanto vamos deixar
> esse ticket ainda aberto e discutiremos esse item na nossa próxima reunião
> para definirmos o preenchimento do país, ok?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scieloorg/scielo-manager/issues/1103#issuecomment-111574634>
> .
>



-- 

Jamil Atta Junior

**Comment by jamilatta** [comment]
Esse ticket está relacionado com #1153.

**Comment by jfunez** [comment]
Continua em #1153
