### ISSUE TITLE
Permissão de acesso de usuários com perfil trainee

### ISSUE THREAD

**Issue by almeida-fabio** [scieloorg/scielo-manager#1104]
Os usuários "trainee" dos técnicos de conversão devem ter também acesso a criação de roles e edição dos campos nas guias "Editor" e "Board" desenvolvidas no Editorial Manager. Atualmente, os técnicos que vão trabalhar com essas alterações são: Carolina Tanigushi (carolina.tanigushi@scielo.org), Felipe Esteves (felipe.esteves@scielo.org) e Isabela Gagliardi (isabela.fonseca@scielo.org).

**Comment by alexxxmendonca** [comment]
Complementando o comentário do Fábio, trata-se de uma necessidade permanente, uma vez que o usuário com perfil "trainee" ficará responsável pela atualização dos corpos editoriais, não somente na alimentação inicial da base, como também de forma contínua daqui para frente.

**Comment by jamilatta** [comment]
Nenhum desses usuários estão cadastrados no SciELO Manager.

**Comment by alexxxmendonca** [comment]
Testado e aprovado em: http://192.168.169.176:8000/

**Comment by jamilatta** [comment]
O usuário isabela.fonseca já existia na base de dados, portanto apenas adicionei ela no grupo **trainee**. Os outros foram criados sem senha é necessário definir uma senha para isso solicito que utilizem o recurso de "Esqueceu sua senha?".

![screen shot 2015-05-27 at 11 41 32](https://cloud.githubusercontent.com/assets/373745/7838808/590b59f6-0465-11e5-889f-a724708887a7.png)
