### ISSUE TITLE
Possibilidade de importação de dados

### ISSUE THREAD

**Issue by almeida-fabio** [scieloorg/scielo-manager#1105]
Já foi conversado em reunião que não há a possibilidade de importação de dados no cadastro dos usuários, abro esse ticket apenas para deixar registrada essa impossibilidade, pois a aplicação não foi desenvolvida com esse propósito.

**Comment by jamilatta** [comment]
@almeida-fabio 

por gentileza defina um formato que acredita ser ideal para essa ações em massa para que possamos avaliar.

**Comment by almeida-fabio** [comment]
@jamilatta , vou verificar com o @alexxxmendonca , a @IsabelaGagliardi e a equipe de produção sobre essa questão. A ideia inicial que foi mencionada na nossa última reunião era a de que talvez fosse mais vantajoso que os dados dos editores fossem incorporados a uma planilha do Excel e esses, por sua vez, fosse então importados para o Editorial Manager.

**Comment by jfunez** [comment]
- referente a exportação dos dados, existe o ticket #1144 
- referente a importação, o modulo não suporta esta funcionalidade e como foi mencionado:

>pois a aplicação não foi desenvolvida com esse propósito.

vou fechar este ticket e caso necessário pode ser aberto novamente ou criar um novo.
