### ISSUE TITLE
E-mails de notificação de alterações

### ISSUE THREAD

**Issue by almeida-fabio** [scieloorg/scielo-manager#1106]
Atualmente estamos recebendo os e-mails de notificação com as alterações feitas na aplicação e por ora seria melhor manter esses e-mails desabilitados devido ao grande número de alterações que serão feitas no início do uso da aplicação com o preenchimento dos dados das revistas do SciELO SP.

**Comment by jamilatta** [comment]
@almeida-fabio 

Utilizando o http://homolog.manager.scielo.org:

por gentileza clique na imagem no canto superior direito, clique no seu e-mail, essa sequência o levará ao perfil do usuário, em **Notifications & Other preferences:**, existe uma opção **Want to receive email notifications?** desmarque e realize alguma alteração em qualquer corpo editorial e verifique se mesmo assim continua recebendo e-mails.

**Comment by almeida-fabio** [comment]
@jamilatta , consegui fazer o teste lá no homolog. Deu certo, não recebi e-mail de notificação da alteração que realizei.

**Comment by jamilatta** [comment]
Então vamos utilizar esse recurso.

**Comment by almeida-fabio** [comment]
@jamilatta , a @IsabelaGagliardi fez um teste com o usuário dela em produção e aparentemente deu certo, ela não recebeu a notificação, mas eu recebi. Entretanto, só teremos a certeza total com o uso da ferramenta e até definirmos a questão do país na nossa próxima reunião, o pessoal da produção não iniciará o preenchimento, pois isso impacta no trabalho deles.

**Comment by jamilatta** [comment]
Iremos manter a idéia de desabilitar a notificação de e-mails por usuário.
