### ISSUE TITLE
Relatórios de dados

### ISSUE THREAD

**Issue by almeida-fabio** [scieloorg/scielo-manager#1107]
Futuramente, a ferramenta poderia permitir a extração de relatórios a serem definidos.

**Comment by jamilatta** [comment]
@almeida-fabio 

por gentileza defina um formato de saída para os relatórios, assim podemos pensar melhor em como produzir esse relatórios.

**Comment by jamilatta** [comment]
Definido com a equipe que uma lista completa(crua) com os dados do corpo editorial por coleção e por revista.

**Comment by jfunez** [comment]
Duplicado, continua em #1144
