### ISSUE TITLE
Integração com API do Orcid para validação

### ISSUE THREAD

**Issue by almeida-fabio** [scieloorg/scielo-manager#1108]
Seria também interessante se nas próximas versões do Editorial Manager houvesse uma integração e validação com os dados do Orcid para verificar se aquele perfil existe e puxar dados para o corpo editorial sendo preenchido.

**Comment by jfunez** [comment]
@almeida-fabio como seria conveniente para vocês a verificação de que o "perfil existe"? 
Porque no cadastro somente o Nome e Email são requeridos, mas o Email pode ficar como visibilidade limitada ou privado, o que não permite a obtenção desse dado pela API pública.

Algo semelhante acontece se no formulário for inserido o id (Orcid) e tentar recuperar dados ("puxar dados"), no caso do id existir, depende da visibilidade dos dados (email, por exemplo) para poder obter ou não os dados, e somente temos garantia de poder obter o primeiro nome.

Então temos as seguintes situações:
- **Usar o nome do member** para recuperar dados do perfil orcid -> geralmente obteríamos  muitos resultados, por exemplo procurando pelo nome "Juan"
- **Usar o email do member** -> a lista de resultados é limitada pela API e o email pode não estar visível publicamente, por padrão é que não esta visível.
- **Usar o orcid do member** -> se a API do orcid retornar algum dado indicaria que existe algum cadastro do lado deles, mas não podemos garantir que os dados são do membro que esta sendo cadastrado, por exemplo um erro de digitação no orcid que existe mas é de outra pessoa, teríamos que cruzar com outro dado, por exemplo o nome e esperar que seja igual, pode parecer uma boa solução, mas se houver alguma diferencia que indique o dado como inválido, pode resultar confuso para o usuário.

**Comment by alexxxmendonca** [comment]
Juan, no sistema que utilizamos de submissão de artigos, o ScholarOne, eles utilzam o ID para fazer esse vínculo. Penso que isso faz mais sentido do que o nome ou o e-mail, até por que o usuário pode ter e-mails diferentes.

Tem também o fato do campo ORCID ficar no final do formulário, portanto supostamente o usuário já teria preenchido os campos anteriores (nome, sobrenome e e-mail), e não faria mais sentido importar esses dados.

Portanto:

a) validamos apenas o ORCID ID e não puxamos mais nenhum dado; ou
b) validamos o ORCID no começo do formulário e puxamos o Nome, sobrenome e e-mail, permitindo que o usuário altere os dados se necessário (erro de digitação ou caso ele queira utilizar outro e-mail).

**Comment by jfunez** [comment]
Então, eu acho que em primeira instância podemos considerar o ponto a)

Faltaria definir o que seria : "validamos apenas o ORCID ID" 
Imagino que é suficiente verificar se existe algum resultado na resposta da API, mesmo que os dados não sejam idênticos. caso que não existe esse ORCID id, seria considerado como inválido

pode ser?

**Comment by alexxxmendonca** [comment]
Juan,

Também no ScholarOne, quando o usuário coloca um ORCID ID válido, o sistema coloca um sinal de "check" do lado, atestando a sua validade. No caso, o ScholarOne se conecta com a API do ORCID para fazer isso.

Podemos começar por aí.

No caso do ScholarOne, o usuário clica em um link que é levado para essa página: https://orcid.org/oauth/signin

Depois de autorizado, ele vincula o ID no campo do ScholarOne.

Não precisamos fazer exatamente igual. No fim das contas o que importa é validar o ORCID ID.

Podemos seguir com a sua sugestão também.

**Comment by jfunez** [comment]
:+1:

**Comment by jfunez** [comment]
no nosso caso, não seria necessário autenticação nem sair do manager, porque vamos usar a API publica mesmo.

**Comment by alexxxmendonca** [comment]
Maravilha! :+1:

**Comment by jfunez** [comment]
Alguns dos ORCID ids que foram testados:
- https://orcid.org/orcid-search/quick-search/?searchQuery=University

**Comment by jfunez** [comment]
Alguns comentários sobre o processo de validação:

Para cada mudança no campo 'ORCID':
 - verifica se o tamanho esta certo (20 chars contando os 4 "-")
 - verifica se atende a regex (o ultimo digito pode ser um "X", ver referencias)
 - verifica se o checksum é valido (ver referencias).

Se atender os 3 requisitos, ainda é feito um request via ajax contra a API de ORCID.
Se a resposta contém dados de um perfil para esse ORCID, então o dado é válido.
Se a resposta é falha, será indicado como ID inválido.

**Atenção:**
As vezes pelo throttling, este passo de validação via API não esta disponível, será indicado como ID inválido.
Tem casos que a API retorna 404 para alguns ordid válidos. mistério! (exemplo: 0000-0002-6444-9718)

Se o conteúdo do campo é vazio, então é considerado como válido também.

referencias:
- http://support.orcid.org/knowledgebase/articles/116780-structure-of-the-orcid-identifier
- https://orcid.github.io/XSD/XSD_1.2_Documentation/orcid-message-1.2.html
- https://en.wiktionary.org/wiki/throttling

**Comment by alexxxmendonca** [comment]
Isso já pode ser testado em ambiente de homologação?

**Comment by jfunez** [comment]
@alexxxmendonca ainda não porque esta em fase de revisão do código. mas em breve vai ficar disponível.

**Comment by jfunez** [comment]
@alexxxmendonca já esta disponível no homolog.scielo.manager a feature de validação de ORCID id.

Tem algumas mudanças respeito ao uso da API, e os critérios aplicados para validar um id.
Então da uma olhada no pull request (https://github.com/scieloorg/scielo-manager/pull/1159) e na mesma descrição do pull request, tem alguns ids que foram testados.
Finalmente, se esta ok para vocês, pode comentar e fechar este issue.
Se achar algo errado, pode criar um novo issue, e adicionar o link aqui como referencia.

aguardamos seus comentários

**Comment by almeida-fabio** [comment]
Testado e aprovado em http://homolog.manager.scielo.org/
