### ISSUE TITLE
analisar atualização de dependências: django-htmlmin e django-cache-machine

### ISSUE THREAD

**Issue by jfunez** [scieloorg/scielo-manager#1111]
#### Diagnostico:
As duas dependências são forks desatualizados. 

- *django-htmlmin*: ``This branch is 48 commits behind cobrateam:master`` 
Este fork tem 2 commits de @jamilatta (aparentemente é um fix) mas o código corrigido já foi removido no projeto original.
- *django-cache-machine*: ``This branch is 25 commits behind django-cache-machine:master`` é também no projeto principal indica que **falta um maintainer**

#### Estratégias:
- *django-htmlmin*: atualizar para o repo oficial (https://github.com/cobrateam/django-htmlmin)
- *django-cache-machine*:  atualizar para o repo oficial (https://github.com/django-cache-machine/django-cache-machine/) ou buscar uma alternativa de outro projeto ativo (https://www.djangopackages.com/grids/g/caching/).

**Comment by jfunez** [comment]
A recomendação de @gustavofonseca é remover o **django-cache-machine**

**Comment by gustavofonseca** [comment]
yeah :+1:

**Comment by jfunez** [comment]
para trabalhar na remoção do **django-cache-machine** foi criado o issue: #1195
