### ISSUE TITLE
Remover o tipo de entidade *journalmanager.models.Article*

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/scielo-manager#1115]
Atualmente o tipo *Article* não é utilizado. Além disso, o branch https://github.com/scieloorg/scielo-manager/tree/1036_integracao_thrift prevê o uso de um tipo de entidade de mesmo nome (*Article*).

Este ticket deve ser considerado um pré requisito para a incorporação do branch https://github.com/scieloorg/scielo-manager/tree/1036_integracao_thrift

**Comment by jamilatta** [comment]
Pelo que entendi esse ticket já foi resolvido, vou fecha-ló qualquer objeção, por favor reabrir.

**Comment by gustavofonseca** [comment]
Foi resolvido sim.
