### ISSUE TITLE
Modelo de Financiamento

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/scielo-manager#1116]
Incluir Model para textos sobre Modelo de Financiamento do periódico.
O modelo de financiamento deve ser datado.

**Comment by jamilatta** [comment]
Acho que precisamos de mais contexto para essa atividade.

**Comment by gustavofonseca** [comment]
O que é o "Modelo de Financiamento do periódico"?

**Comment by jamilatta** [comment]
Pessoal alguém consegue descrever esse ticket... caso contrário irei fecha-lo.

**Comment by gustavofonseca** [comment]
@jamilatta acho que por hora deve ser fechado. Quando houver uma especificação clara, reabrimos.

**Comment by jamilatta** [comment]
:+1:
