### ISSUE TITLE
Incluir dados de instruções aos autores para os periódicos.

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/scielo-manager#1118]
* Incluir instruções aos autores, com data de atualização (ex: texto de missão);
* Tipos de documentos e escopo das pesquisas passíveis de submissão;
* Descrição do procedimento de avação;
* Estrutura dos textos e normas bibliográficas;

**Comment by jamilatta** [comment]
@fabiobatalha 

alguma sugestão de como realizar essa atividade?

**Comment by jamilatta** [comment]
Vou fechar esse ticket até que tenhamos maiores informações.
