### ISSUE TITLE
Lista de Roles indisponível no Editorial Manager {EditorialManager}

### ISSUE THREAD

**Issue by almeida-fabio** [scieloorg/scielo-manager#1120]
Prezados, notamos que estão faltando os roles para cadastro do corpo editorial no http://manager.scielo.org/.

No homolog os roles estão disponíveis, mas não é possível preencher os cadastros no site final sem eles.

**Comment by jamilatta** [comment]
Fábio os roles devem ser criados novamente no ambiente de **produção**, existe inúmeros problemas que teremos que resolver para migrarmos do ambiente de homologação para a produção e na última reunião avisamos dessa impossibilidade.

**Comment by almeida-fabio** [comment]
Então Jamil, como conversamos por tel, esses são os roles considerados Deafult, a lista que definimos entre nós e que vocês subiram para o homolog. Precisamos desses roles para fazer os cadastros iniciais, pois lá em produção não tem nenhum por ora.

**Comment by jamilatta** [comment]
Roles importados no ambiente de produção.
