### ISSUE TITLE
Exportação do corpo editorial em format CSV.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/scielo-manager#1125]
Para integração entre as áreas... iremos permitir que o usuário possa realizar um download de um formato "raw" do corpo editorial por coleção e por revista.

O setor de avaliação usará esses dados para produzir métricas nas avaliações de permanência.

**Comment by jamilatta** [comment]
Formato definido para exportação: 

ID, journal, issn, issue[year], issue[volume], issue[number], role['name'], first_name, last_name, full_name, email, institution, link_cv, state, country, research_id, orcid

**Comment by jamilatta** [comment]
@alexxxmendonca @IsabelaGagliardi  @almeida-fabio e Denise (Acho que a Denise não tem usuário no GitHub)

Por gentileza, poderiam validar no ambiente de homologação o desenvolvimento da Exportação do CSV do Corpo Editorial por Revista e Períodico, ver: http://homolog.manager.scielo.org/editorial/board/25/

Print Screen: 
![screen shot 2015-06-23 at 15 48 37](https://cloud.githubusercontent.com/assets/373745/8314400/b92242d6-19bf-11e5-9d82-490349429f0c.png)

**Comment by alexxxmendonca** [comment]
Minha avaliação é a seguinte:

1) Algumas informações vieram como entidade, ex: Annali dell&#39;Istituto Superiore di Sanità
2) Todos os registros vieram com aspas e isso pode atrapalhar na hora de trabalhar os dados no Excel. Sugiro remover as aspas e trazer apenas o que estiver dentro delas.
3) Houve quebra de dados devido a presença de vírgulas, principalmente no campo "Instituição", fazendo com que os dados sejam separados e exibidos nas colunas seguintes. Como resolver essa questão quando o separador de um CSV é a vírgula?

**Comment by jamilatta** [comment]
Alex segue minhas considerações:

1) OK, iremos ajustar o conjunto de caracteres;

2) As aspas justamente serve para evitar/resolver o item 3, portanto temos
as aspas delimitando o que é dado e a virgula delimitando as colunas;

3) A resposta é utilizando as aspas isso não se torna um problema :-) ;

Para que as aspas não seja um problema, tem uma opção no excel de
importação utilizando aspas nos dados, e virgula entre as colunas.

Irei resolver o item 1.

Qualquer dúvida, podemos importar os CSV juntos.





2015-06-24 11:00 GMT-03:00 alexxxmendonca <notifications@github.com>:

> Minha avaliação é a seguinte:
>
> 1) Algumas informações vieram como entidade, ex: Annali dell'Istituto
> Superiore di Sanità
> 2) Todos os registros vieram com aspas e isso pode atrapalhar na hora de
> trabalhar os dados no Excel. Sugiro remover as aspas e trazer apenas o que
> estiver dentro delas.
> 3) Houve quebra de dados devido a presença de vírgulas, principalmente no
> campo "Instituição", fazendo com que os dados sejam separados e exibidos
> nas colunas seguintes. Como resolver essa questão quando o separador de um
> CSV é a vírgula?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scieloorg/scielo-manager/issues/1125#issuecomment-114877154>
> .
>



-- 

Jamil Atta Junior

**Comment by alexxxmendonca** [comment]
De fato, deu certo marcando "Espaço" como um delimitador, além da vírgula.

**Comment by jamilatta** [comment]
@alexxxmendonca 

por gentileza, verifique no ambiente de homologação se a correção do item 1

http://homolog.manager.scielo.org/editorial/board/25/

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.manager.scielo.org/editorial/board/25/

**Comment by jamilatta** [comment]
Srs, o ambiente de produção esta atualizado com esse recurso.
