### ISSUE TITLE
Bug no componente de seleção dos periódicos.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/scielo-manager#1130]
O componente de seleção de periódico não esta retornando qualquer valor é necessário avaliarmos, ver imagem: 
![screen shot 2015-06-23 at 16 31 18](https://cloud.githubusercontent.com/assets/373745/8315209/4f4f2bac-19c5-11e5-94a4-9fbac2fbbc92.png)

**Comment by gustavofonseca** [comment]
O bug é causado pela ausência do argumento `mimetype` com o valor *application/json* nos objetos *HttpResponse*.

**Comment by jamilatta** [comment]
:+1:

**Comment by gustavofonseca** [comment]
Além disso, as queries realizadas na *view function* **ajx_search_journal** são muito ostentação.. os únicos campos necessários são: *journal.id*, *journal.title*, *journal.print_issn*, *journal.eletronic_issn*, *journal.short_title*, *journal.acronym* e *[collection.name para todo collection em journal.collections]*. Será que conseguimos deixar a query mais enxuta?

**Comment by jamilatta** [comment]
Acredito que a causa desse bug está relacionado com o PR: https://github.com/scieloorg/scielo-manager/pull/1138
