### ISSUE TITLE
Exportação do Board como CSV: observações e melhorias

### ISSUE THREAD

**Issue by jfunez** [scieloorg/scielo-manager#1141]
#### observações:
- link para baixar todo o corpo editorial (``Download as CSV``) pode resultar confuso com o link: ``Export csv``)
- nome do arquivo gerado é igual nos dois casos: ``Download`` e ``Export`` mesmo que um seja do corpo editorial completo, e outro só do issue.
- Etiquetas: ``Download`` para um caso e ``Export`` para outro, parece inconsistente.
- Tooltips: em cada ação é o mesmo: ``Download full list as CSV file.``

#### melhorias:
- mudar: ``Download as CSV`` para ``Export full board as CSV`` e o nome do arquivo deve indicar que é o corpo editorial completo, por exemplo: ``full_board_NOME_DO_PERIODICO``
- mudar: ``Export as csv`` para ``Export this board as CSV`` e o nome do arquivo deve indicar o issue e periódico: ``board_NOME_DO_PERIODICO_ISSUEYEAR_ISSUE_VOLUME_ISSUENUMBER``
- os tooltips não são necessários.

**Comment by jamilatta** [comment]
@jfunez 

verifica no PR: https://github.com/scieloorg/scielo-manager/pull/1129 esses termos foram discutidos  com a equipe e a interface já foi aprovado pela equipe do @alexxxmendonca.

**Comment by jfunez** [comment]
ok @jamilatta, então agora ficaria assim:

#### melhorias:
- mudar: ``Download as CSV`` para ``Download full board as CSV file`` e o nome do arquivo deve indicar que é o corpo editorial completo, por exemplo: ``full_board_NOME_DO_PERIODICO``
- mudar: ``Export as csv`` para ``Download this board as CSV file`` e o nome do arquivo deve indicar o issue e periódico: ``board_NOME_DO_PERIODICO_ISSUEYEAR_ISSUE_VOLUME_ISSUENUMBER``
- os tooltips não são necessários.

**Comment by jamilatta** [comment]
@alexxxmendonca e @almeida-fabio 

vcs acreditam que é necessário essa mudança por gentileza avaliem e respondam para o @juan, grato!

**Comment by alexxxmendonca** [comment]
Sim, as melhorias me parecem adequadas.
