### ISSUE TITLE
Melhorias na janela de input dos dados

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/scielo-manager#1143]
Seria melhor se a janela de inclusão já viesse com o tamanho maximizado, ou então que ela fosse um pouco maior de largura e altura. 

Pelo tamanho default da janela, não é possível ver os campos Country, ResearcherID e ORCID.

Além disso, nas sugestões do Wayta, aumentar um pouco a largura. Muitos nomes de instituições são cortados pela metade.

**Comment by jamilatta** [comment]
Concordo.

**Comment by jfunez** [comment]
Considerar que quando o modal é maximizado, o novo tamanho é proporcional ao tamanho da janela do navegador (deixando margem aos lados do modal)

também:
> Pelo tamanho default da janela, não é possível ver os campos Country, ResearcherID e ORCID.
pelo layout do site, sempre é provável que algum campo (em formulários medianos ou grandes) fiquem fora do "viewport", e foi isso que me levou a fazer o funcionalidade de maximizar/minimizar.

**Comment by alexxxmendonca** [comment]
Sim, estou ciente que nem todos os campos ficarão visíveis -- não é essa a proposta. De qualquer forma, acho o tamanho da janela default muito estreita.
