### ISSUE TITLE
Exportação do corpo editorial em format CSV por alguns filtros.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/scielo-manager#1144]
Em conversa na última reunião com a equipe de avaliação, visualizamos que a equipe será bastante beneficiada com os dados do corpo editorial. 

Sendo assim decidimos que uma listagem "crua" do corpo editorial por coleção e com a possibilidade de filtra por área e estado seria bastante útil.

**Comment by jamilatta** [comment]
Srs, preciso de uma área no SciELO Manager onde o usuário possa realizar extrações/relatórios no nível da coleção. Proponho o seguinte link no manager para acesso a essa área(print screen): 

![screen shot 2015-07-06 at 10 50 40](https://cloud.githubusercontent.com/assets/373745/8523909/5a81d426-23ce-11e5-8760-33b24c9f867a.png)

Alguma idéia melhor? Podemos seguir com essa proposta?

**Comment by jfunez** [comment]
:+1: 
Eu pensei exatamente isso, só que em plural: ``Reports``. 
simplesmente porque estão todos em plural.

**Comment by jamilatta** [comment]
:+1:

**Comment by jamilatta** [comment]
Somente socializando ficaria assim: 
![screen shot 2015-07-06 at 11 51 58](https://cloud.githubusercontent.com/assets/373745/8525152/80e4268a-23d5-11e5-8be5-097bede7e238.png)

**Comment by jamilatta** [comment]
Srs, estou em fase de desenvolvimento desse tiket e me deparei com um **dilema**(não é dilma): adiciono esse desenvolvimento na app journalmanager ou crio uma nova app somente para relatórios, pergunto por que não concordo muito em colocar isso no journalmanager e acho que está na hora de termos uma app para "reports" contemplado todas as apps. :-)

Ajuda dos universitários são bem vindas!

**Comment by jamilatta** [comment]
Vou seguir com a idéia de criar uma nova app chamada **reports**, caso alguém tenha objeção, comenta ai.

**Comment by jamilatta** [comment]
Vou considerar a área de relatórios sem o contexto da coleção, para que seja possível a extração e geração de relatórios sem a necessidade de alteração da coleção.

**Comment by jamilatta** [comment]
Estou pensando em fazer algo assim quando clicado em **Reports**: 

![screen shot 2015-07-06 at 16 38 34](https://cloud.githubusercontent.com/assets/373745/8531417/a0ba90ca-23fd-11e5-8d29-77cd81aee778.png)

**Comment by jamilatta** [comment]
Vou fazer algo mais fácil esse panel na versão 2.3.2 é um "workaround" desnecessário agora.

**Comment by jfunez** [comment]
Utilizando o que vem pronto já no TWBS 2.3.2, minha sugestão é usar nav-list [[1]]
> A simple and easy way to build groups of nav links with optional headers. 

[1]: http://getbootstrap.com/2.3.2/components.html#navs

**Comment by jamilatta** [comment]
:+1:

**Comment by jamilatta** [comment]
Segue mockup para avaliação pela equipe:  

![screen shot 2015-07-07 at 16 17 25](https://cloud.githubusercontent.com/assets/373745/8555006/cde00ce4-24c3-11e5-998d-e4f6defe9e53.png)

**Comment by gustavofonseca** [comment]
A implementação dessa funcionalidade está em https://github.com/scieloorg/scielo-manager/pull/1163
