### ISSUE TITLE
Task para indexar artigos sujos no Elasticsearch.

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/scielo-manager#1145]
Um artigo é considerado "sujo" no período entre a sua modificação no banco de dados e sua indexação no Elasticsearch. Atualmente, o processo de indexação é executado por um callback de *post save* de objetos tipo Article, que por qualquer eventualidade pode falhar. Deve haver uma task periódica que garanta a indexação dos artigos sujos.

**Comment by gustavofonseca** [comment]
Estou pensando em algo como ``process_dirty_articles``, inspirada na task ``process_orphan_articles``.

**Comment by jfunez** [comment]
:+1:

**Comment by jamilatta** [comment]
Show de bola!

On Fri, Jul 3, 2015 at 3:17 PM, Juan Funez <notifications@github.com> wrote:

> [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scieloorg/scielo-manager/issues/1145#issuecomment-118404552>
> .
>



-- 

Jamil Atta Junior

**Comment by gustavofonseca** [comment]
Resolvido em 1736f545824ee3f94d858796338d36dac5a7ef35
