### ISSUE TITLE
RESTFul API e RPC Thrift para o Editorial Manager

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/scielo-manager#1147]
Diante de demandas de exportação/importação do conteúdo do corpo editorial, entendo necessário uma API RestFul e um RPC Thrift para exportação/importação de dados do corpo editorial.

Entendemos que em algum momento devemos expor os dados armazenado no novo layout do site da SciELO.

**Comment by gustavofonseca** [comment]
É fato que será necessário. Entretanto, essa tarefa não deve ser realizada até termos pelo menos 1 caso de uso concreto.

**Comment by jamilatta** [comment]
Acredito que os comentários nesse ticket responde sua pergunta:https://github.com/scieloorg/scielo-manager/issues/1148

 O @jfunez  teve o mesmo questionamento.

**Comment by gustavofonseca** [comment]
Vou fechar esse ticket pois não corresponde a uma demanda concreta.
