### ISSUE TITLE
Licenças conflitantes em base de dados

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/scielo-manager#1158]
As licenças de uso disponíveis para os periódicos esta inconsistente.

Atualmente possuem 4 licenças disponíveis para seleção:

BY
BY-NC
CC-BY-NC
CC-BY-NC-ND

CC-BY-NC é igual a BY-NC.
Para evitar futuros problemas com demais licenças, as licenças que começam com CC devem ser corrigidas para ficar sem a sigla CC no início.

A lista correta seria.
BY
BY-NC
BY-NC-ND

**Comment by fabiobatalha** [comment]
Lembrando que para corrigir o uso da licença CC-BY-NC para BY-NC, será necessário realizar migração de dados.

**Comment by gustavofonseca** [comment]
@fabiobatalha esse ticket já foi resolvido?

**Comment by gustavofonseca** [comment]
@fabiobatalha esse ticket já foi resolvido? PING!
