### ISSUE TITLE
Trocar o separador dos títulos de seções apresentadas no formulário de fascículo

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/scielo-manager#1160]
Sugestões de troca:  --- , |, #, ~~, ou seja, quaisquer caracteres que não existiriam em um título de seção,  etc. Evitar vírgula, ponto-e-vírgula, ponto, etc

Ao listar os títulos das seções do sumário no formulário de fascículo foi usado como separador / para separar as várias traduções. 

O problema é que este separador está presente em alguns títulos de seções, ex.: "Brief Communication / Comunicação Breve". Então, o usuário não consegue distinguir as seções:
```
Brief Communication / Comunicação Breve (csp-5dds)
Comunicação Breve (csp-9ynq) pt
Brief Communication (csp-9ynq) en
```
e acaba selecionando a seção errada, como consequência a seção no site não ficará correta.

Note que no caso aconteceu com csp v31n6. Veja que todas as seções estão com suas correspondentes traduções, exceto 

```
49  "^len^ccsp-5dds^tBrief Communication / Comunicação Breve"
```

que há apenas em inglês.

```
49  "^len^cCSP-sbys^tErratum"
 49  "^len^cCSP-rh53^tLetters"
 49  "^len^cCSP-857h^tArticle"
 49  "^len^cCSP-zf35^tReview"
 49  "^len^cCSP-x5f8^tReviews"
 49  "^len^ccsp-9pcp^tPerspectives"
 49  "^len^ccsp-2wgb^tMethodological Issues"
 49  "^len^ccsp-cxmy^tEditorial (Editor's Choice)"
 49  "^len^ccsp-5dds^tBrief Communication / Comunicação Breve"
 49  "^lpt^cCSP-sbys^tErrata"
 49  "^lpt^cCSP-rh53^tCartas"
 49  "^lpt^cCSP-857h^tArtigo"
 49  "^lpt^cCSP-zf35^tRevisão"
 49  "^lpt^cCSP-x5f8^tResenhas"
 49  "^lpt^ccsp-9pcp^tPerspectivas"
 49  "^lpt^ccsp-2wgb^tQuestões Metodológicas"
 49  "^lpt^ccsp-cxmy^tEditorial (Escolha das Editoras)"
```

**Comment by jamilatta** [comment]
@robertatakenaka 

somente para entendermos melhor em que momento o usuário não consegui distinguir as seções. 

Estamos tentando entender aonde aparece a "/", que criar essa confusão para o usuário.

**Comment by robertatakenaka** [comment]
Há casos em que / faz parte do título. Há casos em que o SciELO Manager
está usando o mesmo caracter (/) para apresentar vários títulos em uma
opção. É isso que causa confusão. A recomendação é que onde o SciELO
Manager está usando /, que ele use outro tipo de "separador".

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639


2016-02-22 14:16 GMT-03:00 Jamil Atta Junior <notifications@github.com>:

**Comment by jfunez** [comment]
@robertatakenaka então seria uma mudança na apresentação (interface) aonde varias sessões são mostradas? 
então, se temos a sessão: "foo/bar" e outra "baz", teriamos que ajustar para mostrar as sessões como: "foo/bar##baz", no lugar de "foo/bar/baz", certo?
a pergunta é em qual parte do manager você identificou essa listagem confusa?
eu procurei na lista de sections do csp por exemplo, e só identifiquei com '/' as que tem um título com '/'.

**Comment by robertatakenaka** [comment]
@jfunez: Exatamente, Juan, é na apresentação de lista para selecionar.

**Comment by jfunez** [comment]
por exemplo esta listagem, certo?

![screenshot 2016-02-22 14 48 55](https://cloud.githubusercontent.com/assets/805749/13227076/793e0f96-d973-11e5-8acf-03518bb28eb2.png)

**Comment by robertatakenaka** [comment]
@jfunez : correto. O SciELO Manager está apresentando os títulos com /. Mas como há título cujo conteúdo já contém /. A seleção da opção fica confusa e o usuário escolhendo o título "similar" mas o código da seção não é o correspondente. Espero que tenha ficado claro agora.

**Comment by jamilatta** [comment]
Grato @robertatakenaka

**Comment by fabiobatalha** [comment]
Acho que é melhor resolver isso com um JS esperto, pq ficar colocando ## como separador. Nenhum usuário merece.

**Comment by fabiobatalha** [comment]
Incluir algum JS que formata a lista, como um Type Ahead que mostre as versões traduzidas de forma mais amigável.

**Comment by jfunez** [comment]
:+1:

**Comment by jamilatta** [comment]
Contextualizando no código onde ocorre a adição do "/": https://github.com/scieloorg/scielo-manager/blob/beta/scielomanager/journalmanager/models.py#L865

**Comment by jfunez** [comment]
resolvido em PR: https://github.com/scieloorg/scielo-manager/pull/1251
