### ISSUE TITLE
Erro ao exibir mensagem traduzida na função *Add new member* 

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/scielo-manager#1161]
![screen shot 2015-07-16 at 10 51 30](https://cloud.githubusercontent.com/assets/161335/8725107/e498b3c8-2ba8-11e5-99dc-94f5bbcb80d0.png)

**Comment by jfunez** [comment]
algumas observações:
- o principal suspeito (localizado no modal.js): 
```python
    $(this).find(".chzn-select").chosen({
      no_results_text: "{% trans 'No results found for' %}:",
      width: "100%",
    });
```
- uma tradução tão simples deveria poder ser feita uma vez só, de forma global, e não para cada inicialização do modal. (investigar se for possível)
- estamos utilizando a versão 1.1.0 e a mais recente até hoje é: 1.4.2 ([ver releases])

[ver releases]: https://github.com/harvesthq/chosen/releases

**Comment by jfunez** [comment]
aparentemente é possível resolver o ponto 2:
> uma tradução tão simples deveria poder ser feita uma vez só, de forma global, 

Definindo uma configuração padrão que seria utilizada em cada inicialização do chosen.
Ver exemplo em: https://github.com/harvesthq/chosen/issues/2279#issuecomment-86690282

```js
var defaultChosenOptions = { 'search_contains': true }

// default options
$(".field1").chosen(defaultChosenOptions);
$(".field2").chosen(defaultChosenOptions);

// no search contains
$(".field3").chosen();
```

Para o caso do Manager, poderíamos definir num template base (base_lv1.html)
```html
{% loadi18n %}
<!-- CÓDIGO HTML -->
<script>
var defaultChosenOptions = { 'no_results_text': "{% trans 'No results found for' %}:" }
</script>
```
Logo, em cada template ou arquivo js, que inicialize o plugin:
```js
$(".fieldX").chosen(defaultChosenOptions);
```
