### ISSUE TITLE
Criação de tasks para viabilizar a reconstrução das chaves de domínio dos artigos.

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/scielo-manager#1183]
Atualmente, por conta da implantação do processo de carga de artigos no SciELO Manager, são necessárias manipulações nos dados de parte ou todas as instâncias de *journalmanager.models.Article*. 

Serão criadas 2 tasks para apoiar o processo de reconstrução das chaves de domínio dos registros:
  * ``journalmanager.tasks.rebuild_article_domain_key``
  * ``journalmanager.tasks.rebuild_articles_domain_key``

A idéia desse ticket é apenas de documentar esses caras.

**Comment by jfunez** [comment]
incorporado em https://github.com/scieloorg/scielo-manager/pull/1184
