### ISSUE TITLE
Erro na task que relaciona artigo com revista.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/scielo-manager#1187]
Analisando o New Relic descobrimos que existe uma exceção não tratada no momento em que a task: ``link_article_to_journal`` tenta associar um artigo com uma revista.

Msg de erro: 
```
journalmanager.models:MultipleObjectsReturned: get() returned more than one Journal -- it returned 193! Lookup parameters were {}
```
OBS.: Suspeitamos que o parâmetro na consulta seja vazio e portanto retorna uma quantidade não esperada. 

Esse tipo de msg não é enviada por e-mail para a equipe, pois o erro ocorre no celeryd e por hora não configuramos de forma a enviar e-mail, mas devemos pesquisar como configurar o log do celeryd para recebermos e-mail (esse último comentário é item obrigatório para essa atividade).

**Comment by jamilatta** [comment]
Atualmente a consulta que estamos realizando retorna todos os campos do models:Journal.

Uma melhoria interessante e apontada pelo @gustavofonseca seria explicitarmos os campos na consulta para baratearmos o tempo de execução da tarefa, segue trecho para modificação: 

https://github.com/scieloorg/scielo-manager/blob/beta/scielomanager/journalmanager/tasks.py#L123-L133

**Comment by jfunez** [comment]
Complementado com informação do stack trace, a linha do erro é 125 do ``tasks.py``:
> ``scielomanager/journalmanager/tasks.py", line 125, in link_article_to_journal``

**Comment by jfunez** [comment]
Acredito que para a melhoria apontada por @gustavofonseca uma opção é utilizar o ``values()`` do QuerySet.

>The values() method takes optional positional arguments, *fields, which specify field names to which the SELECT should be limited. 

doc: https://docs.djangoproject.com/en/1.4/ref/models/querysets/#django.db.models.query.QuerySet.values

**Comment by gustavofonseca** [comment]
@jfunez , o ``values()`` não é o que procuramos. Veja a descrição: *Returns a ValuesQuerySet — a QuerySet subclass that returns dictionaries when used as an iterable, rather than model-instance objects.*

**Comment by jfunez** [comment]
@gustavofonseca sim sim, eu vi depois, e atualizei meu comentário com as outras funções disponíveis: ``defer()`` e ``only()``
