### ISSUE TITLE
remove app: tools

### ISSUE THREAD

**Issue by jfunez** [scieloorg/scielo-manager#1205]
segundo indicações de @gustavofonseca esta app foi criada no gêneses do scielo-manager, e agora não é mais necessária.

**Comment by gustavofonseca** [comment]
Esses códigos são responsáveis pela importação de dados no sistema. Suspeito que alguns scripts sejam utilizados.

**Comment by jfunez** [comment]
Fechado então, até termos uma definição mais detalhada.
