### ISSUE TITLE
Histórico dos periódicos na grade de fascículos

### ISSUE THREAD

**Issue by francine-curivil** [scieloorg/scielo-manager#1215]
Na semana passada um novo periódico entrou na coleção Saúde Pública e ontem percebi que no histórico do periódico na grade de fascículos não está aparecendo a frase "Admitida na Coleção":

RESS na Coleção Saúde Pública: ver imagem 01
RESS na Coleção SciELO Brasil: ver imagem 02.

Essa frase sempre apareceu automaticamente com base na informação que nós colocamos no campo "Data de entrada" na Title antiga (ver imagem 3).

Vocês poderiam ver um jeito de fazê-la aparecer também quando usamos o SciELO Manager?
![01](https://cloud.githubusercontent.com/assets/4871433/9942362/0136fcd6-5d51-11e5-93bd-8347d5aa7a87.jpg)
![02](https://cloud.githubusercontent.com/assets/4871433/9942363/01586b8c-5d51-11e5-9e83-098aa52883c0.jpg)
![03](https://cloud.githubusercontent.com/assets/4871433/9942364/017984f2-5d51-11e5-8c45-993758d72b53.jpg)

**Comment by fabiobatalha** [comment]
@francine-curivil 

Problema corrigido, favor verificar se funcionou após o próximo processamento e atualização do site em produção.

**Comment by francine-curivil** [comment]
@fabiobatalha 

Ainda não está aparecendo corretamente. A informação "Admitido na Coleção" deveria ser apresentada da mesma forma que aparece no SciELO Brasil, mas com a data de inclusão do periódico na coleção SP.

![ress-scielo-br](https://cloud.githubusercontent.com/assets/4871433/10026007/bab11056-6135-11e5-9291-9747d7db182d.jpg)
![ress-scielo-sp](https://cloud.githubusercontent.com/assets/4871433/10026008/bab18bc6-6135-11e5-903d-bcf65642dfbf.jpg)

**Comment by fabiobatalha** [comment]
Ok vamos verificar.

2015-09-22 14:25 GMT-03:00 francine-curivil <notifications@github.com>:

**Comment by gustavofonseca** [comment]
@fabiobatalha e @francine-curivil , esse problema foi solucionado?

**Comment by fabiobatalha** [comment]
Sim Gustavo,

Foram feitos alguns ajustes no Delorean.

Att,

**Comment by gustavofonseca** [comment]
Ok, estou fechando o ticket então.
