### ISSUE TITLE
Regras de Status de Periódicos

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/scielo-manager#1242]
De acordo com exclarecimentos da direção e coordenação, para esse tipo de informação referente ao status de indexação dos periódicos nas coleções SciELO. Todos os desenvolvimentos devem ser orientados as seguintes regras.

Os status de periódicos disponíveis e aceitos são:

?: Inprogress
C: Current
D: Deceased
S: Supended

**Inprogress** se refere aos periódicos que entraram nos sistemas de produção, mas ainda não possuem documentos nem fascículos publicados.

**Current** se refere aos periódicos indexados nas coleções SciELO que produzem e publicam regularmente seus conteúdos sob os critérios SciELO.

**Deceased** se refere aos periódicos que deixaram de existir.

**Suspended** deixará de ser conhecido unicamente como "Suspenso pelo Comitê" e passará a comportar uma gama maior de possibilidades, onde **suspended** (S) poderá ter razões diversas para fins de relatórios internos, as razões que devem ser implementadas para as necessidades atuais são:

**suspended-by-editor** (Suspenso a pedido do Editor)
**suspended-by-committee** (Suspenso a pedido do Comitê Consultivo)
**not-open-access** (Suspenso a pedido do Comitê Consultivo por deixar de ser acesso aberto)

# Atenção

Para as interfaces públicas sempre indicar apenas que o periódico foi suspenso sem detalhar os motivos

**Comment by jfunez** [comment]
@fabiobatalha só um comentário, acho que tem um typo, e no lugar de **suspended-by-comite** seria **suspended-by-committee**

**Comment by fabiobatalha** [comment]
correto @jfunez
