### ISSUE TITLE
Incluir licença de uso no resultado da API de fascículos.

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/scielo-manager#1246]
A falta deste dado faz com que os dados de licenças customizadas de fascículos não sejam replicadas para o site SciELO.

**Comment by gustavofonseca** [comment]
@fabiobatalha: por "API de fascículos" vc quer dizer "no endpoint *issues* da interface Restful"?

**Comment by fabiobatalha** [comment]
Tal como o endpoint journal, indicar a licença de uso da seguinte maneira:

```
"use_license": {
    "disclaimer": "Licencia Creative Commons",
    "id": "1",
    "license_code": "BY-NC",
    "reference_url": null,
    "resource_uri": "/api/v1/uselicenses/1/"
}
```

**Comment by fabiobatalha** [comment]
@gustavofonseca 
Isso

**Comment by lpanebr** [comment]
Esse endpoint me interessa! Está documentado em algum local? Tem um
repositório?

**Comment by gustavofonseca** [comment]
Se você tiver acesso ao manager.scielo.org, dê uma olhada na
documentação
http://docs.scielo.org/projects/scielo-manager/en/latest/dev/api.html



-- 
-Gustavo

Em Sex 19 fev. 2016, às 12:59, Luciano escreveu:

**Comment by lpanebr** [comment]
obrigado gustavo, mas nãoi tenho acesso. Fica para outra oportunidade.
