### ISSUE TITLE
Simplificar o modelo de dados do tipo *journalmanager.Issue* com base na espec. SciELO PS.

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/scielo-manager#1249]
Uma instância tipo *journalmanager.Issue* é representada, fundamentalmente, no SciELO Manager por meio dos atributos:
* volume
* number
* type
* suppl_text
* spe_text

E na especificação SciELO PS por meio dos atributos:
* volume
* issue

A simplificação promovida pela especificação SciELO PS se deve ao fato de que o atributo *issue* é mais abstrato e pode representar números regulares, especiais e suplementos por meio de convenções como: ``Suppl 3``, ``2 Suppl 3`` etc.

**Comment by gustavofonseca** [comment]
Após uma primeira rodada de consulta aos demais desenvolvedores, concluímos que trocar estrutura por convenção abre inúmeras possibilidades de erros de preenchimento e consequênte dificuldade na consulta aos registros. 

Segue trecho do email enviado por Fabio Batalha (10:29 @ scielo-xml-sig) que resume os problemas na abordagem:

> ainda sim teríamos que implementar algumas regras de validação para o campo issue para evitar coisas do tipo.
> 
> 1 suppl. 2
> 1 supl. 2
> 1 suplemento 2
> 1 supplement 2
> 1 sup 2
> 
> Não sei se estaríamos deixando tudo muito susceptível a criatividade dos outros, lembrando que podem haver outras configurações que podem deixar complexa a validação dos dados deste campo, ex:
> 
> 1 spe 2
> 1 special 2
> 
> O suplemento pode ser de volume.
> 
> suppl 1
> suplemento 1
> 
> Não sei se pode haver a combinação
> 
> 1 suppl esp 2
> 
> Existem também casos onde o número não é apenas um número, ou o volume não é apenas um número.
> 
> 1 suppl. 1-2
> 1-2 suppl. 1

**Comment by lpanebr** [comment]
@gustavofonseca [continuando] eu ia te lembrar que a sua sugestão de convenções representava um “vazamento de encapsulamento” (algo que aprendi com vc!). Mas vi que voltaram atrás.

enfim.. acho que precisarão complicar usando o `<supplement>` mesmo..

Ainda mais com as revistas passando mudando para publicação em fluxo contínuo onde, independente do modelo que adotem (apenas volume, volume e número etc), sempre podem publicar edições especiais e/ou suplementares.. Algumas revistas publicam vários suplementos por ano.

**Comment by gustavofonseca** [comment]
rs poisé, foi uma má ideia. Esse parece ser exemplo de caso onde devemos
aumentar a complexidade da estrutura a fim de descomplicar a sua
semântica.

-- 
-Gustavo

Em Ter 23 fev. 2016, às 16:13, Luciano escreveu:
