### ISSUE TITLE
Trocar title_iso por short_title nos arquivos exportados *_issue.mds

### ISSUE THREAD

**Issue by jfunez** [scieloorg/scielo-manager#1286]
#### Problema:
@robertatakenaka reparou que nos arquivos exportados pelo download de Markupfiles, em particular nos arquivos: ``*_issue.mds`` tem diferencia entre as primeiras 2 linhas, mostrando o nome do periódico em formato diferente, como no exemplo enviado por email:

>Oi Juan 

> Pode verificar a questão do título abreviado.
> O título deveria ser o título abreviado comum.
> 
> Nutr. hosp. v.30 n.2
> Nutr. Hosp.;30;;2;;20140800;0212-1611;1
> Originals | Originales;Reviews | Revisiones;Clinical Cases | Casos Clínicos;Obituary | Necrológica;Sín título de sección
> nh-9hfw;nh-mjx2;nh-7xfj;nh-tfry;nd
> Ningun Descriptor
> other standard
> 
> 
> Roberta Takenaka

#### Objetivo:
Ajustar para que nas dias primeiras lineas, para mostrar o ``short_title`` do periódico.

**Comment by gustavofonseca** [comment]
O que é _título abreviado comum_? No fragmento acima são exibidos os títulos (em ordem): ISO abbreviated title e Short Title.

**Comment by robertatakenaka** [comment]
Short Title
