### ISSUE TITLE
Campos e botões para tradução

### ISSUE THREAD

**Issue by javani** [scieloorg/scielo-manager#1301]
@jamilatta Conforme conversamos, alguns campos e botões no Manager não estão disponíveis para tradução no transifex. Estou construindo manual de usuário e estes dados precisam ser traduzidos. São eles:

**Botões em todas as páginas**
remove
add another

**Campos**

**Em registro do periódico:**
_ISSN:_
Print issn
Eletronic issn

_Asunto:_
study areas
Subject categories

_Idiomas:_
Abstract keyword languages

_Información del sistema:_
CCN Code

**Em registro de número:**
Use license
Section

**Em registro de seção:**
_Información de la sección:_
Legacy code

**Em registro de Press Release**
_Configuraciones:_
Issue

_Contenido:_
Body
Preview as HTML

**Em registro de estado da coleção**

_Cambiar estado:_
Current
Deceased
Suspended
In progress

Reason

**Em registro de corpo editorial:**
Download full board as CSV file

**Comment by jamilatta** [comment]
@javani @solange-scielo

estou realizando essa atividade.

**Comment by jamilatta** [comment]
Verifiquei que a tradução dos termos: 
Print issn
Eletronic issn

Estão disponíveis e já traduzidos, ver: 
<img width="1440" alt="screenshot 2016-08-24 10 56 14" src="https://cloud.githubusercontent.com/assets/373745/17933207/9114c900-69e9-11e6-8d15-0017e7c76aad.png">

**Comment by javani** [comment]
@jamilatta no contexto da apresentação do título em About sim, mas dentro do grupo de campos do ISSN não. Veja:
![image](https://cloud.githubusercontent.com/assets/912953/17933363/2e154748-69ea-11e6-9c0d-f54a861997b5.png)

![image](https://cloud.githubusercontent.com/assets/912953/17933374/3aa85c84-69ea-11e6-89e9-6d476845752f.png)

**Comment by jamilatta** [comment]
@javani 

entendi estou verificando.

**Comment by jamilatta** [comment]
Resolvido vamos para o outro.
