### ISSUE TITLE
[Manager] Excluir ponto em número especial

### ISSUE THREAD

**Issue by javani** [scieloorg/scielo-manager#1302]
Ao cadastrar número especial no manager, inclui automaticamente um ponto ao final "spe.". Quando tentamos subir o número para homolog, não o reconhece na base.
![image](https://cloud.githubusercontent.com/assets/912953/17530097/6d4fed18-5e4c-11e6-96ea-b49bf4a320d7.png)

Acrescentando o ponto no elemento `<issue>`o mesmo subiu. Como padrão não usamos ponto ao final do número, apesar de se tratar de uma abreviação. Seria possível verificar? No site final aparece como "special issue".

http://homolog.xml.scielosp.org/reports/not_registered/2237-9622-ress-25-spe/xml_converter.html

**Comment by javani** [comment]
No site está incluir o ponto:
![image](https://cloud.githubusercontent.com/assets/912953/17530960/2e21be7e-5e50-11e6-8836-48f3a0fce65a.png)

**Comment by javani** [comment]
@jamilatta apenas um adendo a esse ticket. Quando tentamos converter os arquivos, os mesmos não são reconhecidos porque a pasta onde estão os dados não possuem ponto ao final de seu nome. Mesmo que coloquemos o ponto na nomeação da pasta o mesmo é excluído automaticamente pelo windows.

**Comment by javani** [comment]
@jamilatta @gustavofonseca não seria possível incluir o número especial como número regular, eliminando essa opção do manager? Pelo menos a questão do ponto seria resolvida e não teríamos problemas na conversão com os issues. Fiz um teste em homolog e o registro foi executado com sucesso. Também baixei os dados de issue que seria usado para marcação e o dado veio certo tb. 
[Uploading issue.mds…]()

**Comment by gustavofonseca** [comment]
Suspeito que o erro esteja no método https://github.com/scieloorg/scielo-manager/blob/beta/scielomanager/journalmanager/models.py#L994

**Comment by jamilatta** [comment]
@gustavofonseca verifiquei com a @javani ela me relatou que em nenhuma condição deve existir o "." (ponto)

**Comment by jamilatta** [comment]
@gustavofonseca também não é algo tão urgente, portanto podemos ver isso depois.

**Comment by gustavofonseca** [comment]
Legal. Valeu @jamilatta!

**Comment by gustavofonseca** [comment]
@javani, então exemplos corretos seriam: ``spe``, ``spe3``, ``25 (spe)`` e ``25 (spe3)``?

**Comment by javani** [comment]
@gustavofonseca isso, isso, isso.

**Comment by gustavofonseca** [comment]
@javani 👍
