### ISSUE TITLE
Download de metadados para marcação de periódico novo

### ISSUE THREAD

**Issue by javani** [scieloorg/scielo-manager#1413]
Considerando a possibilidade de implementação da coleção do Equador, iniciei testei de marcação de um periódico ainda em fase de inclusão (in progress). Como insumo, usei a Revista Baiana de Enfermagem que faz parte da coleção RevEnf e que encontra-se nesse estado, ou seja, não possui números vinculados.
Como não há como baixar os dados da nuvem (tanto por ser uma coleção que não faz parte da rede como em fase inicial de implementação), é possível usar os dados do arquivo journal-standard.txt com dados básicos do periódico o qual faz parte do pacote zipado disponível no item de download do manager. 
Ocorre que o arquivo desse periódico específico veio com os seguintes dados:
2178-8650#Rev. baiana enferm.#vancouv#epub#2178-8650#Health Sciences###**Rev. baiana enferm.**#rbaen#0102-5430#2178-8650#Universidade Federal da Bahia
Ou seja, o título completo não está sendo recuperado para gerar esse arquivos. 
O correto seria:
2178-8650#Rev. baiana enferm.#vancouv#epub#2178-8650#Health Sciences###Revista Baiana de Enfermagem#rbaen#0102-5430#2178-8650#Universidade Federal da Bahia
Acredito que o problema esteja relacionado a ausência de números para um periódico específico, mas como trata-se de uma coleção que ainda irá iniciar a operação, o natural é que os números ainda não existam no manager, os quais apenas serão registrados após o primeiro envio.
De qualquer forma para iniciar a marcação usando nosso programa, o dado deverá estar completo. Seria possível verificar?

**Comment by gustavofonseca** [comment]
Você está falando que existem casos onde a fucionalidade "Download -> Metadados para Markup" produz um pacote cujo arquivo `journal-standard.txt` apresenta um erro no campo referente ao título completo. Certo?

**Comment by javani** [comment]
Isso Gustavo, quando da ausência de números vinculados ao titulo.

Javani Araujo
*SciELO Brasil*
*FAPESP - CNPq - BIREME - **FAP UNIFESP*
*Av. Onze de Junho, 269*
*04041-050 - São Paulo-SP - Brasil*
*Tel.: 55-11-5083-3639*
*www.scielo.org <http://www.scielo.org/> | www.scielo.br
<http://www.scielo.br/> | blog.scielo.org <http://blog.scielo.org/>*

[Atenção: A versão 1.4 do SciELO PS, foi descontinuada em 18 de abril de
2017. Por gentileza, passem a utilizar a versão 1.5 ou 1.6 do SPS
<http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/>. / A
versão XPM com datas de relatórios 21/11/2016 e 16/12/2016, serão
descontinuadas em *18 de maio de 2017*. Por gentileza, passem a utilizar a
versão *17/04/2017*.]

2017-05-15 11:43 GMT-03:00 Gustavo Fonseca <notifications@github.com>:

**Comment by gustavofonseca** [comment]
Na realidade o erro ocorre sempre que no menu dropdown "Número" é selecionado um número ahead of print.
