### ISSUE TITLE
Acceso a scielo-manager

### ISSUE THREAD

**Issue by cesardmoro** [scieloorg/scielo-manager#1424]
Hola, quería acceder a scielo manager para poder listar los contenidos desde una aplicación externa, es esto posible ?

**Comment by gustavofonseca** [comment]
278/5000
Si ya es usuario del sistema, posible a través de la interfaz Restful. Más información en https://github.com/scieloorg/scielo-manager/blob/beta/docs/dev/restful_api/api.rst y los demás archivos en https://github.com/scieloorg/scielo-manager/tree/beta/docs/dev/restful_api.

**Comment by cesardmoro** [comment]
Gustavo, DIsculpas por reabrir el tema, pero no soy usuario.

Como puedo registrarme como usuario?

**Comment by gustavofonseca** [comment]
Ticket relacionado ao #1425.
