### ISSUE TITLE
Crear usuario para scielo manager

### ISSUE THREAD

**Issue by cesardmoro** [scieloorg/scielo-manager#1425]
Como puedo obtener un usuario para scielo manager

**Comment by gustavofonseca** [comment]
SciELO Manager es un software de gestión de catálogo, para uso exclusivo de las unidades SciELO y no por usuarios interesados en hacer uso de los datos. Para el público en general vale la recomendación dada en la lista [scielo-dev](https://groups.google.com/d/msg/scielo-dev/bIkgB2p6oEQ/NjjMURVdAgAJ).
