### ISSUE TITLE
[Style Checker] Valores tag <product>

### ISSUE THREAD

**Issue by alexxpsilva** [scieloorg/scielo-manager#1427]
Não valida os valores abaixo da [tag product](http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/master/tagset/elemento-product.html)

article | artigo
-- | --
issue | fascículo
website | site ou blog
film | filme
software | programa de computador
hardware | componente físico de computador

Aparece a mensagem abaixo.

![style_product](https://user-images.githubusercontent.com/15328777/37094379-76cba07a-21f1-11e8-9b41-506e8f5527d6.png)

Já o valor "other" é validado, e também é validado contra as regras SciELO Brasil

**Comment by RPostalli** [comment]
@robertatakenaka @gustavofonseca lembrando que esta questão foi uma das correções para SPS 1.8, estávamos obrigando uma regra SciELO para todos indevidamente.
Mais detalhes ver na master, tag product e ver em Regras Brasil tag product também.

**Comment by alexxpsilva** [comment]
Ticket fechado por ser aberto no diretório incorreto.

Aberto [ticket](https://github.com/scieloorg/packtools/issues/141) no packtools
