### ISSUE TITLE
Reimplementar o Ahead of Print (deve ser feito até o final de 2013)

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/scielo-manager#409]
Foi desenvolvido uma forma alternativa de prover infra-estrutura para os issues do tipo ahead, porém essa solução funcionará somente para este ano 2013 o que obriga encontrarmos uma solução ainda para este ano.

Soluções:

* Criar uma entidade separada que atenda as características do ahead vinculado ao journal e não ser mais um issue do tipo ahead.

* Criar uma rotina anual que cria ahead para cada journal mantendo o ahead de um ano atrás.

**Comment by gustavofonseca** [comment]
Ticket obsoleto.
