### ISSUE TITLE
Editor Manager

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/scielo-manager#532]
Discussão sobre formas de implementação e integração das aplicações de Editor Manager no contexto do SciELO Manager.

**Abordagens**

* Inclusão como uma app no projeto SciELO Manager do Django.
* Desenvolvimento em um novo projeto integrando com o Journal Manager através de API's.

Documentação completa desta discussão em (acesso apenas com e-mail scielo): 
https://docs.google.com/a/scielo.org/document/d/1n7ffnjSxKEBxuWGNDewhslenZrob5VDUOGjutyYtGrY/edit?usp=sharing

**Comment by jfunez** [comment]
Feito!

**Comment by jamilatta** [comment]
Hecho.

On Wed, May 27, 2015 at 6:27 PM, Juan Funez <notifications@github.com>
wrote:

> Feito!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scieloorg/scielo-manager/issues/532#issuecomment-106084660>
> .
>



-- 

Jamil Atta Junior
