### ISSUE TITLE
Criar *modelmanagers* de *journalmanager.Article*.

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/scielo-manager#603]

**Comment by jfunez** [comment]
Já foi criado um novo modelo de article, na app: journal_manager e o respectivo modelmanager:
https://github.com/scieloorg/scielo-manager/blob/1036_integracao_thrift/scielomanager/journalmanager/modelmanagers.py#L189
Será incorporado com as mudanzas da nova arquitetura.
