### ISSUE TITLE
Adicionar contador dos ``status`` das notificações

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/scielo-manager#658]
Em conversa com a equipe de produção foi discutido a possibilidade de incluir um contador de ``status`` das notificações.

**Comment by jfunez** [comment]
A app  **articletrack** sera removida do branch principal (ver: #1085). Ergo, o ponto de integração do Manager com o Balaio, e as notificações deixaria de ser relevante por enquanto.

**Comment by jfunez** [comment]
App removida em PR: #1094
Caso seja reincorporada pode reabrir este issue.
