### ISSUE TITLE
Melhorar o componente ``Article`` na area de filtragem em ``Article in submission``

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/scielo-manager#777]
O listbox ``Article`` na area de filtragem irá crescer bastante, por isso acredito que devemos ter um item que saiba lidar com essa quantidade de artigos, facilitando a vida do usuário.

**Comment by jfunez** [comment]
A app  **articletrack** sera removida do branch principal (ver: #1085). Ergo, esta filtragem junto com o componente Article deixaria de ser relevante por enquanto.

**Comment by jfunez** [comment]
App removida em PR: #1094
Caso seja reincorporada pode reabrir este issue.
