### ISSUE TITLE
Refatoração da classe *articletrack.balaio.BalaioRPC* para atender mudanças no servidor

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/scielo-manager#824]
Ver as discussões em https://github.com/scieloorg/balaio/pull/330

**Comment by jfunez** [comment]
A app  **articletrack** sera removida do branch principal (ver: #1085). Ergo, o ponto de integração do Manager com o Balaio deixaria de ser relevante por enquanto.

**Comment by jfunez** [comment]
App removida em PR: #1094
Caso seja reincorporada pode reabrir este issue.
