### ISSUE TITLE
Adicionar recurso de monitoramento no Celery

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/scielo-manager#925]
Analisando e estudando sobre o assunto verifiquei que não é possível adicionar um software de monitoramento no celery utilizando como broker o Django.

Ver: http://celery.readthedocs.org/en/latest/userguide/monitoring.html e http://celery.readthedocs.org/en/latest/getting-started/brokers/django.html

**Comment by jfunez** [comment]
[IMPEDIDO] até resolver a setup do RabbitMQ.

**Comment by jfunez** [comment]
atualização:
- homolog continua utilizando postgres como backend
- produção já conta com RabbitMQ
