### ISSUE TITLE
Criar app: audit log

### ISSUE THREAD

**Issue by jfunez** [scieloorg/scielo-manager#951]
segundo a descrição nos documentos

**Comment by gustavofonseca** [comment]
@jfunez na descrição você diz: segundo a descrição nos documentos. Quais documentos?

**Comment by jfunez** [comment]
Documento (no Google Drive): **editorial_manager_app_scielo_manager**, seção **Requisitos:**, ponto **5**.

> Armazenar logs das alterações realizadas pelo editor garantido a rastreabilidade pela equipe de produção;

O documento já foi compartilhado, mas caso precisar uma copia ou o link de aceso fico a disposição.

**Comment by gustavofonseca** [comment]
Achei, valeu!

**Comment by jfunez** [comment]
:beers:
