### ISSUE TITLE
Adicionar permissões no grupo Editors e Librarian

### ISSUE THREAD

**Issue by jfunez** [scieloorg/scielo-manager#971]
- ``editorialmanager.change_editorialmember`` para permitir a edição de board members
- ``editorialmanager.add_editorialmember`` para permitir adicionar um novo board member
- ``editorialmanager.delete_editorialmember`` para permitir apagar um board member

A mudança tem que ser aplicada nos grupos: **Editors** e **Librarian**.
E deve ser editado o json do fixture.

Além disso, tem que adicionar somente para o Librarian:
- ``journalmanager.change_editor`` para poder trocar o usuário **editor** de um periódico.
- ``journalmanager.list_editor_journal`` para poder listar os editores possíveis.

**Comment by jamilatta** [comment]
Srs, 

em consequência aos últimos ajustes realizados na aplicação EditorialManager esse ticket acabou sendo realizado, portanto, tanto no ambiente de homologação quando no ambiente de produção as permissões foram ajustadas.
