### ISSUE TITLE
Adicionar novos campos no formulário Journal disponibilizado para o editor

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/scielo-manager#976]
Analisando os campos da entidade Journal, descobrimos que é necessário adicionar os seguintes campos:

``` python
    publisher_name = models.CharField(_('Publisher Name'), max_length=256)
    publisher_country = modelfields.CountryField(_('Publisher Country'))
    publisher_state = models.CharField(_('Publisher State/Province/Region'), max_length=64)
    publication_city = models.CharField(_('Publication City'), max_length=64)
```

**Comment by gustavofonseca** [comment]
@jamilatta, qual a justificativa para a existência desses campos? Nesse ticket vc só diz que descobriu serem necessários, mas não compartilhou nada sobre essa descoberta.

**Comment by jamilatta** [comment]
@gustavofonseca 

preciso relembrar..., vou verificar juntamente com o @jfunez. Em breve adiciono comentários aqui :+1: ?

**Comment by gustavofonseca** [comment]
Blz. Como estou lidando com esse assunto, eu ficaria grato se vc puder não demorar muito para verificar. =]

**Comment by jamilatta** [comment]
Sim estou vendo agora.

**Comment by jamilatta** [comment]
@gustavofonseca 

para não gerar confusão preciso esclarecer que a frase inicial do tk não contextualiza o suficiente:

Frase original: "Analisando os campos da entidade Journal, descobrimos que é necessário adicionar os seguintes campos:"

Deveria de ser: "Analisando **com a equipe do @alexxxmendonca** os campos **existentes na** entidade Journal, descobrimos que é necessário adicionar os seguintes campos **no formulário de edição do periódico para o perfil editor**"

Resumindo esse ticket não adiciona os campos publisher_* no modelo, esse tk adiciona os campos **publisher_** no formulário de Journal destinado ao perfil editor, portanto a criação desses campos aconteceram em outro momento, agora a justificativa para que o editor possa alterar esses dados é baseada na justificativa inicial do editormanager em que o editor "chefe" sabe melhor do que ninguém sobre dados da revista e o publisher_* são alguns deles.

Respondendo a pergunta: Não sei o por que da existência desses campos precisa verificar no ticket que realmente criou esses campos.

**Comment by gustavofonseca** [comment]
Blz, valeu! Vou continuar investigando rs.

**Comment by jamilatta** [comment]
:+1:
